package com.example.generadordiagramas.analizador;
// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

import java_cup.runtime.*;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\1\22\0\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\2\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\43\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\2\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\43\1\61\1\70\1\71"+
    "\1\72\1\73\6\0\1\3\252\0\2\74\115\0\1\75"+
    "\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\2\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\16\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\2\1\1\40\1\0\1\41\1\2\1\0"+
    "\5\42\1\43\1\0\1\44\1\45\1\46\3\26\1\0"+
    "\3\26\1\0\6\26\1\0\3\26\2\47\1\26\1\0"+
    "\2\26\1\50\2\0\3\42\1\0\1\42\1\51\1\26"+
    "\1\0\2\26\1\0\1\26\1\0\1\26\2\52\3\26"+
    "\1\0\3\26\2\0\4\26\1\0\1\53\1\26\1\54"+
    "\3\42\1\0\1\42\1\26\1\0\2\26\2\0\1\26"+
    "\1\0\3\26\2\0\3\26\1\0\1\55\2\26\2\0"+
    "\4\26\1\0\1\26\3\42\1\0\1\42\2\56\2\26"+
    "\2\0\1\26\1\0\2\26\1\0\2\57\1\26\1\60"+
    "\1\26\1\0\2\26\2\0\2\26\1\61\1\26\1\0"+
    "\1\26\3\42\1\0\1\42\2\26\2\0\2\62\2\26"+
    "\1\0\1\26\2\63\2\26\2\0\3\26\1\0\1\26"+
    "\3\42\1\0\1\42\1\64\1\26\1\0\1\64\2\26"+
    "\1\0\1\65\1\26\2\66\1\0\3\26\1\0\1\67"+
    "\4\42\1\0\1\70\1\42\1\0\3\42\1\0\1\26"+
    "\1\0\2\71\1\26\1\0\2\72\3\26\1\0\2\42"+
    "\1\0\2\73\4\42\3\0\2\42\1\0\2\74\1\26"+
    "\1\0\1\26\1\0\3\26\1\0\2\42\1\0\3\42"+
    "\1\0\2\75\1\0\2\42\1\0\1\42\1\0\2\76"+
    "\1\26\1\0\1\26\1\77\1\26\1\0\2\42\1\0"+
    "\3\42\2\0\2\42\1\0\1\42\1\0\2\100\3\26"+
    "\1\0\2\42\1\0\3\42\2\0\2\42\1\0\1\42"+
    "\1\0\3\26\1\0\1\101\1\42\1\0\3\42\2\0"+
    "\1\102\1\42\1\0\3\42\3\0\1\103\2\26\1\0"+
    "\1\42\1\0\3\42\1\0\1\104\1\42\1\0\1\104"+
    "\1\42\1\0\2\42\1\0\2\105\1\0\2\26\1\0"+
    "\2\106\2\42\1\0\2\107\1\42\1\0\2\110\2\42"+
    "\2\0\1\26\2\111\2\42\1\0\2\112\2\42\2\0"+
    "\1\26\2\42\1\0\2\42\2\0\1\26\2\42\1\0"+
    "\1\113\1\42\1\0\1\113\1\26\1\114\1\42\1\0"+
    "\1\42\1\0\1\26\1\42\1\0\2\115\1\26\2\116"+
    "\1\117";

  private static int [] zzUnpackAction() {
    int [] result = new int[445];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\76\0\u0174"+
    "\0\u01b2\0\76\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\u01f0\0\76\0\76\0\u022e\0\u026c\0\u02aa\0\76\0\76"+
    "\0\u02e8\0\u0326\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a"+
    "\0\u04d8\0\u0516\0\u0554\0\u0592\0\u05d0\0\u060e\0\76\0\76"+
    "\0\76\0\76\0\76\0\76\0\u064c\0\76\0\76\0\u068a"+
    "\0\u06c8\0\76\0\u0706\0\76\0\76\0\u0744\0\u0782\0\u07c0"+
    "\0\u07fe\0\u083c\0\u087a\0\76\0\u08b8\0\76\0\76\0\76"+
    "\0\u08f6\0\u0934\0\u0972\0\u09b0\0\u09ee\0\u0a2c\0\u0a6a\0\u0aa8"+
    "\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98"+
    "\0\u0cd6\0\u0d14\0\u0326\0\76\0\u0d52\0\u0d90\0\u0dce\0\u0e0c"+
    "\0\76\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80\0\u0fbe"+
    "\0\u08b8\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u1170"+
    "\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360"+
    "\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512\0\u1550"+
    "\0\u158e\0\u0326\0\u15cc\0\76\0\u160a\0\u1648\0\u1686\0\u16c4"+
    "\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838\0\u1876\0\u18b4"+
    "\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea\0\u1a28\0\u1a66\0\u1aa4"+
    "\0\u1ae2\0\u1b20\0\u0326\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56"+
    "\0\u1c94\0\u1cd2\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca\0\u1e08\0\u1e46"+
    "\0\u1e84\0\u1ec2\0\u0326\0\76\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba"+
    "\0\u1ff8\0\u2036\0\u2074\0\u20b2\0\u20f0\0\u0326\0\76\0\u212e"+
    "\0\u0326\0\u216c\0\u21aa\0\u21e8\0\u2226\0\u2264\0\u22a2\0\u22e0"+
    "\0\u231e\0\u0326\0\u235c\0\u239a\0\u23d8\0\u2416\0\u2454\0\u2492"+
    "\0\u24d0\0\u250e\0\u254c\0\u258a\0\u25c8\0\u2606\0\u0326\0\76"+
    "\0\u2644\0\u2682\0\u26c0\0\u26fe\0\u0326\0\76\0\u273c\0\u277a"+
    "\0\u27b8\0\u27f6\0\u2834\0\u2872\0\u28b0\0\u28ee\0\u292c\0\u296a"+
    "\0\u29a8\0\u29e6\0\u2a24\0\u2a62\0\u0326\0\u2aa0\0\u2ade\0\76"+
    "\0\u2b1c\0\u2b5a\0\u2b98\0\u0326\0\u2bd6\0\u0326\0\76\0\u2c14"+
    "\0\u2c52\0\u2c90\0\u2cce\0\u2d0c\0\u0326\0\u2d4a\0\u2d88\0\u2dc6"+
    "\0\u2e04\0\u2e42\0\u0782\0\u2e80\0\u2ebe\0\u2efc\0\u2f3a\0\u2f78"+
    "\0\u2fb6\0\u2ff4\0\u3032\0\u0326\0\76\0\u3070\0\u30ae\0\u0326"+
    "\0\76\0\u30ec\0\u312a\0\u3168\0\u31a6\0\u31e4\0\u3222\0\u3260"+
    "\0\u0782\0\76\0\u329e\0\u32dc\0\u331a\0\u3358\0\u3396\0\u33d4"+
    "\0\u3412\0\u3450\0\u348e\0\u34cc\0\u350a\0\u3548\0\u3586\0\u35c4"+
    "\0\u3602\0\u3640\0\u367e\0\u36bc\0\u36fa\0\u3738\0\u3776\0\u37b4"+
    "\0\u37f2\0\u3830\0\u386e\0\u38ac\0\u38ea\0\u0782\0\76\0\u3928"+
    "\0\u3966\0\u39a4\0\u39e2\0\u3a20\0\u3a5e\0\u0326\0\76\0\u3a9c"+
    "\0\u3ada\0\u3b18\0\u3b56\0\u3b94\0\u3bd2\0\u3c10\0\u3c4e\0\u3c8c"+
    "\0\u3cca\0\u3d08\0\u3d46\0\u3d84\0\u3dc2\0\u3e00\0\u3e3e\0\u3e7c"+
    "\0\u3eba\0\u3ef8\0\u0326\0\76\0\u3f36\0\u3f74\0\u3fb2\0\u3ff0"+
    "\0\u402e\0\u406c\0\u40aa\0\u40e8\0\u4126\0\u4164\0\u41a2\0\u41e0"+
    "\0\u421e\0\u425c\0\u429a\0\u42d8\0\u4316\0\u4354\0\u4392\0\u43d0"+
    "\0\u440e\0\u0782\0\u444c\0\u448a\0\u44c8\0\u4506\0\u4544\0\u4582"+
    "\0\u45c0\0\u0782\0\u45fe\0\u463c\0\u467a\0\u46b8\0\u46f6\0\u4734"+
    "\0\u4772\0\u47b0\0\u0326\0\u47ee\0\u482c\0\u486a\0\u48a8\0\u48e6"+
    "\0\u4924\0\u4962\0\u49a0\0\u49de\0\u0782\0\u4a1c\0\u4a5a\0\76"+
    "\0\u4a98\0\u4ad6\0\u4b14\0\u4b52\0\u4b90\0\u0782\0\76\0\u4bce"+
    "\0\u4c0c\0\u4c4a\0\u4c88\0\u0782\0\76\0\u4cc6\0\u4d04\0\u4d42"+
    "\0\u0782\0\76\0\u4d80\0\u4dbe\0\u0782\0\76\0\u4dfc\0\u4e3a"+
    "\0\u4e78\0\u4eb6\0\u4ef4\0\u0326\0\76\0\u4f32\0\u4f70\0\u4fae"+
    "\0\u0782\0\76\0\u4fec\0\u502a\0\u5068\0\u50a6\0\u50e4\0\u5122"+
    "\0\u5160\0\u519e\0\u51dc\0\u521a\0\u5258\0\u5296\0\u52d4\0\u5312"+
    "\0\u5350\0\u538e\0\u0782\0\u53cc\0\u540a\0\76\0\u5448\0\u0782"+
    "\0\u5486\0\u54c4\0\u5502\0\u5540\0\u557e\0\u55bc\0\u55fa\0\u0782"+
    "\0\76\0\u5638\0\u0782\0\76\0\u0326";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[445];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\2"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\32\1\34\1\35\1\32"+
    "\1\36\1\37\1\32\1\40\1\41\2\32\1\42\1\32"+
    "\1\43\1\44\1\45\1\32\1\46\3\32\1\47\1\50"+
    "\1\51\1\52\1\32\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\77\0\2\3\121\0\1\62\47\0\2\5"+
    "\1\63\2\5\1\64\70\5\2\6\1\65\73\6\10\0"+
    "\1\66\21\0\2\67\1\70\1\71\1\67\1\72\4\67"+
    "\1\73\15\67\4\0\1\67\20\0\1\74\104\0\1\75"+
    "\1\0\1\21\101\0\1\76\75\0\1\77\75\0\1\100"+
    "\71\0\1\32\7\0\20\32\1\101\7\32\4\0\1\32"+
    "\31\0\1\32\7\0\30\32\4\0\1\32\31\0\1\32"+
    "\7\0\10\32\1\102\4\32\1\103\12\32\4\0\1\32"+
    "\5\0\1\104\23\0\1\32\7\0\12\32\1\105\1\32"+
    "\1\106\13\32\4\0\1\32\31\0\1\32\7\0\10\32"+
    "\1\107\17\32\4\0\1\32\5\0\1\110\23\0\1\111"+
    "\7\0\1\112\5\111\22\32\4\0\1\32\31\0\1\32"+
    "\7\0\14\32\1\113\13\32\4\0\1\32\31\0\1\32"+
    "\7\0\4\32\1\114\23\32\4\0\1\32\31\0\1\32"+
    "\7\0\10\32\1\115\4\32\1\116\12\32\4\0\1\32"+
    "\5\0\1\117\23\0\1\32\7\0\1\120\27\32\4\0"+
    "\1\32\31\0\1\32\7\0\4\32\1\121\10\32\1\122"+
    "\12\32\4\0\1\32\31\0\1\32\7\0\10\32\1\123"+
    "\17\32\4\0\1\32\5\0\1\124\23\0\1\32\7\0"+
    "\10\32\1\125\17\32\4\0\1\32\5\0\1\126\23\0"+
    "\1\32\7\0\1\127\3\32\1\130\23\32\4\0\1\32"+
    "\100\0\1\131\52\0\1\132\71\0\1\124\31\0\1\124"+
    "\1\0\5\63\1\64\70\63\10\0\1\133\107\0\1\67"+
    "\7\0\30\67\4\0\1\67\31\0\1\67\7\0\15\67"+
    "\1\134\12\67\4\0\1\67\31\0\1\67\7\0\4\67"+
    "\1\135\23\67\4\0\1\67\31\0\1\67\7\0\10\67"+
    "\1\136\17\67\4\0\1\67\5\0\1\137\23\0\1\67"+
    "\7\0\4\67\1\140\23\67\4\0\1\67\31\0\1\141"+
    "\75\0\1\32\7\0\10\32\1\142\17\32\4\0\1\32"+
    "\5\0\1\143\23\0\1\32\7\0\20\32\1\144\7\32"+
    "\4\0\1\32\31\0\1\32\7\0\13\32\1\145\14\32"+
    "\4\0\1\32\61\0\1\146\45\0\1\32\7\0\10\32"+
    "\1\147\17\32\4\0\1\32\5\0\1\150\23\0\1\32"+
    "\7\0\22\32\1\151\5\32\4\0\1\32\31\0\1\32"+
    "\7\0\14\32\1\152\13\32\4\0\1\32\55\0\1\153"+
    "\51\0\1\154\7\0\6\154\22\32\4\0\1\32\31\0"+
    "\1\154\7\0\2\154\1\155\3\154\22\32\4\0\1\32"+
    "\31\0\1\32\7\0\10\32\1\156\17\32\4\0\1\32"+
    "\5\0\1\157\23\0\1\32\7\0\4\32\1\160\23\32"+
    "\4\0\1\32\31\0\1\32\7\0\4\32\1\161\23\32"+
    "\4\0\1\32\31\0\1\32\7\0\21\32\1\162\6\32"+
    "\4\0\1\32\6\0\1\163\36\0\1\164\61\0\1\32"+
    "\7\0\20\32\1\165\7\32\4\0\1\32\31\0\1\32"+
    "\7\0\2\32\1\166\25\32\4\0\1\32\31\0\1\32"+
    "\7\0\13\32\1\167\14\32\4\0\1\32\31\0\1\32"+
    "\7\0\13\32\1\170\14\32\4\0\1\32\54\0\1\171"+
    "\52\0\1\32\7\0\20\32\1\172\7\32\4\0\1\32"+
    "\31\0\1\32\7\0\20\32\1\173\7\32\4\0\1\32"+
    "\51\0\1\157\31\0\1\157\11\0\1\174\107\0\1\67"+
    "\7\0\12\67\1\175\15\67\4\0\1\67\31\0\1\67"+
    "\7\0\5\67\1\176\22\67\4\0\1\67\31\0\1\67"+
    "\7\0\6\67\1\177\21\67\4\0\1\67\47\0\1\200"+
    "\57\0\1\67\7\0\22\67\1\201\5\67\4\0\1\67"+
    "\31\0\1\32\7\0\1\202\27\32\4\0\1\32\41\0"+
    "\1\203\65\0\1\32\7\0\2\32\1\204\25\32\4\0"+
    "\1\32\31\0\1\32\7\0\10\32\1\205\17\32\4\0"+
    "\1\32\5\0\1\206\35\0\1\207\63\0\1\32\7\0"+
    "\16\32\1\210\11\32\4\0\1\32\57\0\1\211\47\0"+
    "\1\32\7\0\15\32\1\212\12\32\4\0\1\32\31\0"+
    "\1\32\7\0\13\32\1\213\5\32\1\214\6\32\4\0"+
    "\1\32\6\0\1\215\45\0\1\216\5\0\1\215\21\0"+
    "\1\215\22\0\1\217\7\0\6\217\22\32\4\0\1\32"+
    "\31\0\1\217\7\0\4\217\1\220\1\217\22\32\4\0"+
    "\1\32\31\0\1\32\7\0\2\32\1\221\25\32\4\0"+
    "\1\32\43\0\1\222\63\0\1\32\7\0\20\32\1\223"+
    "\7\32\4\0\1\32\31\0\1\32\7\0\14\32\1\224"+
    "\13\32\4\0\1\32\31\0\1\32\7\0\22\32\1\225"+
    "\5\32\4\0\1\32\63\0\1\226\67\0\1\227\51\0"+
    "\1\32\7\0\1\230\27\32\4\0\1\32\31\0\1\32"+
    "\7\0\22\32\1\231\5\32\4\0\1\32\31\0\1\32"+
    "\7\0\1\32\1\232\26\32\4\0\1\32\31\0\1\32"+
    "\7\0\4\32\1\233\23\32\4\0\1\32\45\0\1\234"+
    "\61\0\1\32\7\0\3\32\1\235\24\32\4\0\1\32"+
    "\31\0\1\67\7\0\15\67\1\236\12\67\4\0\1\67"+
    "\31\0\1\67\7\0\1\237\27\67\4\0\1\67\31\0"+
    "\1\67\7\0\23\67\1\240\4\67\4\0\1\67\64\0"+
    "\1\241\42\0\1\67\7\0\20\67\1\242\7\67\4\0"+
    "\1\67\31\0\1\32\7\0\12\32\1\243\15\32\4\0"+
    "\1\32\53\0\1\244\53\0\1\32\7\0\23\32\1\245"+
    "\4\32\4\0\1\32\31\0\1\32\7\0\2\32\1\246"+
    "\25\32\4\0\1\32\43\0\1\247\116\0\1\250\42\0"+
    "\1\32\7\0\21\32\1\251\6\32\4\0\1\32\6\0"+
    "\1\252\53\0\1\252\21\0\1\252\22\0\1\32\7\0"+
    "\14\32\1\253\13\32\4\0\1\32\31\0\1\32\7\0"+
    "\10\32\1\254\17\32\4\0\1\32\5\0\1\255\23\0"+
    "\1\32\7\0\10\32\1\256\17\32\4\0\1\32\5\0"+
    "\1\257\43\0\1\257\31\0\1\257\43\0\1\255\31\0"+
    "\1\255\23\0\1\260\7\0\6\260\22\32\4\0\1\32"+
    "\31\0\1\260\7\0\6\260\12\32\1\261\7\32\4\0"+
    "\1\32\31\0\1\32\7\0\10\32\1\262\17\32\4\0"+
    "\1\32\5\0\1\263\43\0\1\263\31\0\1\263\23\0"+
    "\1\32\7\0\22\32\1\264\5\32\4\0\1\32\31\0"+
    "\1\32\7\0\20\32\1\265\7\32\4\0\1\32\61\0"+
    "\1\266\77\0\1\267\43\0\1\32\7\0\12\32\1\270"+
    "\15\32\4\0\1\32\31\0\1\32\7\0\1\271\27\32"+
    "\4\0\1\32\31\0\1\32\7\0\15\32\1\272\12\32"+
    "\4\0\1\32\31\0\1\32\7\0\21\32\1\273\6\32"+
    "\4\0\1\32\6\0\1\274\53\0\1\274\21\0\1\274"+
    "\22\0\1\32\7\0\1\275\27\32\4\0\1\32\31\0"+
    "\1\67\7\0\20\67\1\276\7\67\4\0\1\67\31\0"+
    "\1\67\7\0\23\67\1\277\4\67\4\0\1\67\31\0"+
    "\1\67\7\0\20\67\1\300\7\67\4\0\1\67\61\0"+
    "\1\301\45\0\1\67\7\0\1\302\27\67\4\0\1\67"+
    "\31\0\1\32\7\0\12\32\1\303\15\32\4\0\1\32"+
    "\31\0\1\32\7\0\30\32\4\0\1\304\75\0\1\305"+
    "\53\0\1\306\53\0\1\32\7\0\4\32\1\307\23\32"+
    "\4\0\1\32\45\0\1\310\61\0\1\32\7\0\2\32"+
    "\1\311\25\32\4\0\1\32\31\0\1\32\7\0\4\32"+
    "\1\312\23\32\4\0\1\32\45\0\1\313\61\0\1\314"+
    "\7\0\6\314\22\32\4\0\1\32\31\0\1\32\7\0"+
    "\15\32\1\315\12\32\4\0\1\32\56\0\1\316\50\0"+
    "\1\32\7\0\20\32\1\317\7\32\4\0\1\32\31\0"+
    "\1\32\7\0\1\320\27\32\4\0\1\32\41\0\1\321"+
    "\115\0\1\322\45\0\1\32\7\0\4\32\1\323\23\32"+
    "\4\0\1\32\31\0\1\32\7\0\14\32\1\324\13\32"+
    "\4\0\1\32\31\0\1\32\7\0\30\32\4\0\1\325"+
    "\75\0\1\326\31\0\1\32\7\0\14\32\1\327\13\32"+
    "\4\0\1\32\31\0\1\67\7\0\30\67\4\0\1\330"+
    "\31\0\1\67\7\0\12\67\1\331\15\67\4\0\1\67"+
    "\31\0\1\67\7\0\1\332\27\67\4\0\1\67\41\0"+
    "\1\333\65\0\1\67\7\0\30\67\4\0\1\334\31\0"+
    "\1\32\7\0\15\32\1\335\12\32\4\0\1\32\31\0"+
    "\1\32\7\0\21\32\1\336\6\32\4\0\1\32\6\0"+
    "\1\337\53\0\1\337\21\0\1\337\47\0\1\340\50\0"+
    "\1\32\7\0\4\32\1\341\23\32\4\0\1\32\31\0"+
    "\1\32\7\0\14\32\1\342\13\32\4\0\1\32\55\0"+
    "\1\343\51\0\1\344\7\0\6\344\22\32\4\0\1\32"+
    "\31\0\1\32\7\0\1\345\27\32\4\0\1\32\31\0"+
    "\1\32\7\0\20\32\1\346\7\32\4\0\1\32\61\0"+
    "\1\347\55\0\1\350\65\0\1\32\7\0\12\32\1\351"+
    "\15\32\4\0\1\32\31\0\1\32\7\0\6\32\1\352"+
    "\21\32\4\0\1\32\31\0\1\32\7\0\14\32\1\353"+
    "\13\32\4\0\1\32\55\0\1\354\51\0\1\32\7\0"+
    "\1\355\27\32\4\0\1\32\31\0\1\67\7\0\1\67"+
    "\1\356\11\67\1\357\5\67\1\360\1\361\5\67\4\0"+
    "\1\67\6\0\1\362\22\0\1\67\7\0\22\67\1\363"+
    "\5\67\4\0\1\67\31\0\1\67\7\0\30\67\4\0"+
    "\1\364\75\0\1\365\31\0\1\67\7\0\1\67\1\366"+
    "\11\67\1\367\5\67\1\370\6\67\4\0\1\67\6\0"+
    "\1\371\22\0\1\32\7\0\1\372\27\32\4\0\1\32"+
    "\41\0\1\373\65\0\1\32\7\0\21\32\1\374\6\32"+
    "\4\0\1\32\6\0\1\375\22\0\1\32\7\0\22\32"+
    "\1\376\5\32\4\0\1\32\63\0\1\377\43\0\1\32"+
    "\7\0\21\32\1\u0100\6\32\4\0\1\32\6\0\1\u0101"+
    "\53\0\1\u0101\21\0\1\u0101\22\0\1\32\7\0\15\32"+
    "\1\u0102\12\32\4\0\1\32\31\0\1\32\7\0\23\32"+
    "\1\u0103\4\32\4\0\1\32\31\0\1\32\7\0\4\32"+
    "\1\u0104\23\32\4\0\1\32\45\0\1\u0105\61\0\1\67"+
    "\7\0\12\67\1\u0106\15\67\4\0\1\67\31\0\1\67"+
    "\7\0\10\67\1\u0107\17\67\4\0\1\67\5\0\1\u0108"+
    "\23\0\1\67\7\0\10\67\1\u0109\17\67\4\0\1\67"+
    "\5\0\1\u010a\23\0\1\67\7\0\4\67\1\u010b\23\67"+
    "\4\0\1\67\51\0\1\u010a\31\0\1\u010a\23\0\1\67"+
    "\7\0\1\67\1\u010c\11\67\1\u010d\5\67\1\u010e\6\67"+
    "\4\0\1\67\6\0\1\u010f\33\0\1\u0110\11\0\1\u0111"+
    "\5\0\1\u010f\21\0\1\u010f\22\0\1\67\7\0\12\67"+
    "\1\u0112\15\67\4\0\1\67\31\0\1\67\7\0\10\67"+
    "\1\u0113\17\67\4\0\1\67\5\0\1\u0114\23\0\1\67"+
    "\7\0\10\67\1\u0115\17\67\4\0\1\67\5\0\1\u0116"+
    "\43\0\1\u0116\31\0\1\u0116\23\0\1\32\7\0\14\32"+
    "\1\u0117\13\32\4\0\1\32\55\0\1\u0118\51\0\1\32"+
    "\7\0\20\32\1\u0119\7\32\4\0\1\32\61\0\1\u011a"+
    "\45\0\1\32\7\0\6\32\1\u011b\21\32\4\0\1\32"+
    "\31\0\1\32\7\0\12\32\1\u011c\15\32\4\0\1\32"+
    "\31\0\1\32\7\0\25\32\1\u011d\2\32\4\0\1\32"+
    "\66\0\1\u011e\40\0\1\67\7\0\15\67\1\u011f\12\67"+
    "\4\0\1\67\31\0\1\67\7\0\4\67\1\u0120\23\67"+
    "\4\0\1\67\45\0\1\u0121\61\0\1\67\7\0\26\67"+
    "\1\u0122\1\67\4\0\1\67\31\0\1\67\7\0\12\67"+
    "\1\u0123\15\67\4\0\1\67\31\0\1\67\7\0\10\67"+
    "\1\u0124\17\67\4\0\1\67\5\0\1\u0125\23\0\1\67"+
    "\7\0\10\67\1\u0126\17\67\4\0\1\67\5\0\1\u0127"+
    "\43\0\1\u0127\31\0\1\u0127\45\0\1\u0128\73\0\1\u0125"+
    "\31\0\1\u0125\23\0\1\67\7\0\15\67\1\u0129\12\67"+
    "\4\0\1\67\31\0\1\67\7\0\4\67\1\u012a\23\67"+
    "\4\0\1\67\45\0\1\u012b\61\0\1\67\7\0\27\67"+
    "\1\u012c\4\0\1\67\70\0\1\u012d\36\0\1\32\7\0"+
    "\21\32\1\u012e\6\32\4\0\1\32\6\0\1\u012f\53\0"+
    "\1\u012f\21\0\1\u012f\22\0\1\32\7\0\1\u0130\27\32"+
    "\4\0\1\32\41\0\1\u0131\65\0\1\32\7\0\20\32"+
    "\1\u0132\7\32\4\0\1\32\31\0\1\32\7\0\15\32"+
    "\1\u0133\12\32\4\0\1\32\31\0\1\32\7\0\30\32"+
    "\4\0\1\u0134\75\0\1\u0135\31\0\1\67\7\0\17\67"+
    "\1\u0136\10\67\4\0\1\67\31\0\1\67\7\0\14\67"+
    "\1\u0137\13\67\4\0\1\67\55\0\1\u0138\51\0\1\67"+
    "\7\0\22\67\1\u0139\5\67\4\0\1\67\31\0\1\67"+
    "\7\0\15\67\1\u013a\12\67\4\0\1\67\31\0\1\67"+
    "\7\0\4\67\1\u013b\23\67\4\0\1\67\45\0\1\u013c"+
    "\106\0\1\u013d\50\0\1\67\7\0\17\67\1\u013e\10\67"+
    "\4\0\1\67\31\0\1\67\7\0\14\67\1\u013f\13\67"+
    "\4\0\1\67\55\0\1\u0140\51\0\1\67\7\0\4\67"+
    "\1\u0141\23\67\4\0\1\67\45\0\1\u0142\61\0\1\32"+
    "\7\0\21\32\1\u0143\6\32\4\0\1\32\6\0\1\u0144"+
    "\53\0\1\u0144\21\0\1\u0144\22\0\1\32\7\0\1\u0145"+
    "\27\32\4\0\1\32\31\0\1\32\7\0\30\32\4\0"+
    "\1\u0146\31\0\1\32\7\0\20\32\1\u0147\7\32\4\0"+
    "\1\32\61\0\1\u0148\45\0\1\67\7\0\23\67\1\u0149"+
    "\4\67\4\0\1\67\31\0\1\67\7\0\22\67\1\u014a"+
    "\5\67\4\0\1\67\63\0\1\u014b\43\0\1\67\7\0"+
    "\15\67\1\u014c\12\67\4\0\1\67\31\0\1\67\7\0"+
    "\17\67\1\u014d\10\67\4\0\1\67\31\0\1\67\7\0"+
    "\14\67\1\u014e\13\67\4\0\1\67\55\0\1\u014f\100\0"+
    "\1\u0150\46\0\1\67\7\0\23\67\1\u0151\4\67\4\0"+
    "\1\67\31\0\1\67\7\0\22\67\1\u0152\5\67\4\0"+
    "\1\67\63\0\1\u0153\43\0\1\67\7\0\30\67\4\0"+
    "\1\u0154\75\0\1\u0155\31\0\1\32\7\0\13\32\1\u0156"+
    "\14\32\4\0\1\32\31\0\1\32\7\0\20\32\1\u0157"+
    "\7\32\4\0\1\32\31\0\1\32\7\0\15\32\1\u0158"+
    "\12\32\4\0\1\32\56\0\1\u0159\50\0\1\67\7\0"+
    "\4\67\1\u015a\23\67\4\0\1\67\31\0\1\67\7\0"+
    "\20\67\1\u015b\7\67\4\0\1\67\61\0\1\u015c\45\0"+
    "\1\67\7\0\30\67\4\0\1\u015d\31\0\1\67\7\0"+
    "\23\67\1\u015e\4\67\4\0\1\67\31\0\1\67\7\0"+
    "\22\67\1\u015f\5\67\4\0\1\67\63\0\1\u0160\76\0"+
    "\1\u0161\42\0\1\67\7\0\4\67\1\u0162\23\67\4\0"+
    "\1\67\31\0\1\67\7\0\20\67\1\u0163\7\67\4\0"+
    "\1\67\61\0\1\u0164\45\0\1\67\7\0\1\67\1\u0165"+
    "\11\67\1\u0166\5\67\1\u0167\6\67\4\0\1\67\6\0"+
    "\1\u0168\33\0\1\u0169\11\0\1\u016a\5\0\1\u0168\21\0"+
    "\1\u0168\22\0\1\32\7\0\15\32\1\u016b\12\32\4\0"+
    "\1\32\31\0\1\32\7\0\4\32\1\u016c\23\32\4\0"+
    "\1\32\31\0\1\32\7\0\13\32\1\u016d\14\32\4\0"+
    "\1\32\54\0\1\u016e\52\0\1\67\7\0\1\u016f\27\67"+
    "\4\0\1\67\41\0\1\u0170\65\0\1\67\7\0\1\67"+
    "\1\u0171\11\67\1\u0172\5\67\1\u0173\6\67\4\0\1\67"+
    "\6\0\1\u0174\22\0\1\67\7\0\4\67\1\u0175\23\67"+
    "\4\0\1\67\31\0\1\67\7\0\20\67\1\u0176\7\67"+
    "\4\0\1\67\61\0\1\u0177\61\0\1\u0178\61\0\1\67"+
    "\7\0\1\u0179\27\67\4\0\1\67\41\0\1\u017a\65\0"+
    "\1\67\7\0\12\67\1\u017b\15\67\4\0\1\67\31\0"+
    "\1\67\7\0\10\67\1\u017c\17\67\4\0\1\67\5\0"+
    "\1\u017d\23\0\1\67\7\0\10\67\1\u017e\17\67\4\0"+
    "\1\67\5\0\1\u017f\43\0\1\u017f\31\0\1\u017f\45\0"+
    "\1\u0180\73\0\1\u017d\31\0\1\u017d\23\0\1\32\7\0"+
    "\3\32\1\u0181\24\32\4\0\1\32\31\0\1\32\7\0"+
    "\1\u0182\27\32\4\0\1\32\41\0\1\u0183\65\0\1\67"+
    "\7\0\21\67\1\u0184\6\67\4\0\1\67\6\0\1\u0185"+
    "\53\0\1\u0185\21\0\1\u0185\22\0\1\67\7\0\12\67"+
    "\1\u0186\15\67\4\0\1\67\31\0\1\67\7\0\10\67"+
    "\1\u0187\17\67\4\0\1\67\5\0\1\u0188\23\0\1\67"+
    "\7\0\10\67\1\u0189\17\67\4\0\1\67\5\0\1\u018a"+
    "\43\0\1\u018a\31\0\1\u018a\23\0\1\67\7\0\1\u018b"+
    "\27\67\4\0\1\67\41\0\1\u018c\65\0\1\67\7\0"+
    "\21\67\1\u018d\6\67\4\0\1\67\6\0\1\u018e\53\0"+
    "\1\u018e\21\0\1\u018e\22\0\1\67\7\0\15\67\1\u018f"+
    "\12\67\4\0\1\67\31\0\1\67\7\0\4\67\1\u0190"+
    "\23\67\4\0\1\67\45\0\1\u0191\106\0\1\u0192\50\0"+
    "\1\32\7\0\15\32\1\u0193\12\32\4\0\1\32\31\0"+
    "\1\32\7\0\14\32\1\u0194\13\32\4\0\1\32\55\0"+
    "\1\u0195\51\0\1\67\7\0\15\67\1\u0196\12\67\4\0"+
    "\1\67\31\0\1\67\7\0\4\67\1\u0197\23\67\4\0"+
    "\1\67\45\0\1\u0198\61\0\1\67\7\0\21\67\1\u0199"+
    "\6\67\4\0\1\67\6\0\1\u019a\53\0\1\u019a\21\0"+
    "\1\u019a\22\0\1\67\7\0\17\67\1\u019b\10\67\4\0"+
    "\1\67\31\0\1\67\7\0\14\67\1\u019c\13\67\4\0"+
    "\1\67\55\0\1\u019d\100\0\1\u019e\46\0\1\32\7\0"+
    "\14\32\1\u019f\13\32\4\0\1\32\31\0\1\67\7\0"+
    "\17\67\1\u01a0\10\67\4\0\1\67\31\0\1\67\7\0"+
    "\14\67\1\u01a1\13\67\4\0\1\67\55\0\1\u01a2\51\0"+
    "\1\67\7\0\23\67\1\u01a3\4\67\4\0\1\67\31\0"+
    "\1\67\7\0\22\67\1\u01a4\5\67\4\0\1\67\63\0"+
    "\1\u01a5\76\0\1\u01a6\42\0\1\32\7\0\3\32\1\u01a7"+
    "\24\32\4\0\1\32\31\0\1\67\7\0\23\67\1\u01a8"+
    "\4\67\4\0\1\67\31\0\1\67\7\0\22\67\1\u01a9"+
    "\5\67\4\0\1\67\63\0\1\u01aa\43\0\1\67\7\0"+
    "\4\67\1\u01ab\23\67\4\0\1\67\31\0\1\67\7\0"+
    "\20\67\1\u01ac\7\67\4\0\1\67\61\0\1\u01ad\61\0"+
    "\1\u01ae\61\0\1\32\7\0\4\32\1\u01af\23\32\4\0"+
    "\1\32\31\0\1\67\7\0\4\67\1\u01b0\23\67\4\0"+
    "\1\67\31\0\1\67\7\0\20\67\1\u01b1\7\67\4\0"+
    "\1\67\61\0\1\u01b2\45\0\1\67\7\0\1\u01b3\27\67"+
    "\4\0\1\67\41\0\1\u01b4\65\0\1\32\7\0\1\u01b5"+
    "\27\32\4\0\1\32\31\0\1\67\7\0\1\u01b6\27\67"+
    "\4\0\1\67\41\0\1\u01b7\65\0\1\67\7\0\21\67"+
    "\1\u01b8\6\67\4\0\1\67\6\0\1\u01b9\53\0\1\u01b9"+
    "\21\0\1\u01b9\22\0\1\32\7\0\3\32\1\u01ba\24\32"+
    "\4\0\1\32\31\0\1\67\7\0\21\67\1\u01bb\6\67"+
    "\4\0\1\67\6\0\1\u01bc\53\0\1\u01bc\21\0\1\u01bc"+
    "\22\0\1\32\7\0\15\32\1\u01bd\12\32\4\0\1\32"+
    "\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[22134];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\2\1\7\11\1\1\2\11"+
    "\3\1\2\11\16\1\6\11\1\1\2\11\2\1\1\11"+
    "\1\0\2\11\1\0\5\1\1\11\1\0\3\11\3\1"+
    "\1\0\3\1\1\0\6\1\1\0\4\1\1\11\1\1"+
    "\1\0\2\1\1\11\2\0\3\1\1\0\3\1\1\0"+
    "\2\1\1\0\1\1\1\0\6\1\1\0\3\1\2\0"+
    "\4\1\1\0\2\1\1\11\3\1\1\0\2\1\1\0"+
    "\2\1\2\0\1\1\1\0\3\1\2\0\3\1\1\0"+
    "\3\1\2\0\4\1\1\0\4\1\1\0\2\1\1\11"+
    "\2\1\2\0\1\1\1\0\2\1\1\0\1\1\1\11"+
    "\3\1\1\0\2\1\2\0\4\1\1\0\4\1\1\0"+
    "\3\1\2\0\1\1\1\11\2\1\1\0\2\1\1\11"+
    "\2\1\2\0\3\1\1\0\4\1\1\0\3\1\1\0"+
    "\1\11\2\1\1\0\3\1\1\11\1\0\3\1\1\0"+
    "\5\1\1\0\2\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\11\3\1\1\0"+
    "\2\1\1\0\1\1\1\11\4\1\3\0\2\1\1\0"+
    "\3\1\1\0\1\1\1\0\3\1\1\0\2\1\1\0"+
    "\3\1\1\0\1\1\1\11\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\0\3\1\1\0\2\1"+
    "\1\0\3\1\2\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\11\3\1\1\0\2\1\1\0\3\1\2\0\2\1"+
    "\1\0\1\1\1\0\3\1\1\0\2\1\1\0\3\1"+
    "\2\0\2\1\1\0\3\1\3\0\3\1\1\0\1\1"+
    "\1\0\3\1\1\0\2\1\1\0\1\11\1\1\1\0"+
    "\2\1\1\0\1\1\1\11\1\0\2\1\1\0\1\1"+
    "\1\11\2\1\1\0\1\1\1\11\1\1\1\0\1\1"+
    "\1\11\2\1\2\0\2\1\1\11\2\1\1\0\1\1"+
    "\1\11\2\1\2\0\3\1\1\0\2\1\2\0\3\1"+
    "\1\0\2\1\1\0\1\11\3\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\11\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[445];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public static class ErrorLexico
    {
        public String lexema;
        public int linea;
        public int columna;
        public String descripcion;

        public ErrorLexico(String lexema, int linea, int columna, String descripcion)
        {
            this.lexema = lexema;
            this.linea = linea;
            this.columna = columna;
            this.descripcion = descripcion;
        }
    }

    public ArrayList<ErrorLexico> listaErrores = new ArrayList<>();
    private Symbol symbol(int type, Object value)
    {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    private void reportarError(String lexema, String descripcion)
    {
        listaErrores.add(new ErrorLexico(lexema, yyline + 1, yycolumn + 1, descripcion));
        System.err.println("Error Léxico en línea " + (yyline + 1) + ", columna " + (yycolumn + 1) + ": " + descripcion + " '" + lexema + "'");
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { reportarError(yytext(), "Token no reconocido");
            }
          // fall through
          case 80: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 81: break;
          case 3:
            { return symbol(sym.NOT, yytext());
            }
          // fall through
          case 82: break;
          case 4:
            { reportarError(yytext(), "Cadena sin cerrar - falta comilla de cierre");
            }
          // fall through
          case 83: break;
          case 5:
            { reportarError(yytext(), "Carácter '$' no permitido en el lenguaje");
            }
          // fall through
          case 84: break;
          case 6:
            { reportarError(yytext(), "Carácter '&' no permitido en el lenguaje (use '&&' para AND)");
            }
          // fall through
          case 85: break;
          case 7:
            { return symbol(sym.PAR_IZQ, yytext());
            }
          // fall through
          case 86: break;
          case 8:
            { return symbol(sym.PAR_DER, yytext());
            }
          // fall through
          case 87: break;
          case 9:
            { return symbol(sym.POR, yytext());
            }
          // fall through
          case 88: break;
          case 10:
            { return symbol(sym.MAS, yytext());
            }
          // fall through
          case 89: break;
          case 11:
            { return symbol(sym.COMA, yytext());
            }
          // fall through
          case 90: break;
          case 12:
            { return symbol(sym.MENOS, yytext());
            }
          // fall through
          case 91: break;
          case 13:
            { return symbol(sym.DIV, yytext());
            }
          // fall through
          case 92: break;
          case 14:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 93: break;
          case 15:
            { reportarError(yytext(), "Carácter ':' no permitido en el lenguaje");
            }
          // fall through
          case 94: break;
          case 16:
            { reportarError(yytext(), "Carácter ';' no permitido en el lenguaje");
            }
          // fall through
          case 95: break;
          case 17:
            { return symbol(sym.MENOR, yytext());
            }
          // fall through
          case 96: break;
          case 18:
            { return symbol(sym.IGUAL_ASIG, yytext());
            }
          // fall through
          case 97: break;
          case 19:
            { return symbol(sym.MAYOR, yytext());
            }
          // fall through
          case 98: break;
          case 20:
            { reportarError(yytext(), "Carácter '?' no permitido en el lenguaje");
            }
          // fall through
          case 99: break;
          case 21:
            { reportarError(yytext(), "Carácter '@' no permitido en el lenguaje");
            }
          // fall through
          case 100: break;
          case 22:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 101: break;
          case 23:
            { reportarError(yytext(), "Carácter '[' no permitido en el lenguaje");
            }
          // fall through
          case 102: break;
          case 24:
            { reportarError(yytext(), "Carácter '\\' no permitido en el lenguaje");
            }
          // fall through
          case 103: break;
          case 25:
            { reportarError(yytext(), "Carácter ']' no permitido en el lenguaje");
            }
          // fall through
          case 104: break;
          case 26:
            { reportarError(yytext(), "Carácter '^' no permitido en el lenguaje");
            }
          // fall through
          case 105: break;
          case 27:
            { reportarError(yytext(), "Carácter '`' no permitido en el lenguaje");
            }
          // fall through
          case 106: break;
          case 28:
            { reportarError(yytext(), "Carácter '{' no permitido en el lenguaje");
            }
          // fall through
          case 107: break;
          case 29:
            { return symbol(sym.PIPE, yytext());
            }
          // fall through
          case 108: break;
          case 30:
            { reportarError(yytext(), "Carácter '}' no permitido en el lenguaje");
            }
          // fall through
          case 109: break;
          case 31:
            { reportarError(yytext(), "Carácter '~' no permitido en el lenguaje");
            }
          // fall through
          case 110: break;
          case 32:
            { return symbol(sym.DIFERENTE, yytext());
            }
          // fall through
          case 111: break;
          case 33:
            { return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 112: break;
          case 34:
            { reportarError(yytext(), "Configuración no reconocida");
            }
          // fall through
          case 113: break;
          case 35:
            { return symbol(sym.AND, yytext());
            }
          // fall through
          case 114: break;
          case 36:
            { return symbol(sym.MENOR_IGUAL, yytext());
            }
          // fall through
          case 115: break;
          case 37:
            { return symbol(sym.IGUALDAD, yytext());
            }
          // fall through
          case 116: break;
          case 38:
            { return symbol(sym.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 117: break;
          case 39:
            { return symbol(sym.SI, yytext());
            }
          // fall through
          case 118: break;
          case 40:
            { return symbol(sym.OR, yytext());
            }
          // fall through
          case 119: break;
          case 41:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 120: break;
          case 42:
            { return symbol(sym.FIN, yytext());
            }
          // fall through
          case 121: break;
          case 43:
            { return symbol(sym.VAR, yytext());
            }
          // fall through
          case 122: break;
          case 44:
            { return symbol(sym.SEPARADOR, yytext());
            }
          // fall through
          case 123: break;
          case 45:
            { return symbol(sym.LEER, yytext());
            }
          // fall through
          case 124: break;
          case 46:
            { return symbol(sym.FONT_ARIAL, yytext());
            }
          // fall through
          case 125: break;
          case 47:
            { return symbol(sym.FINSI, yytext());
            }
          // fall through
          case 126: break;
          case 48:
            { return symbol(sym.HACER, yytext());
            }
          // fall through
          case 127: break;
          case 49:
            { return symbol(sym.FIG_ROMBO, yytext());
            }
          // fall through
          case 128: break;
          case 50:
            { return symbol(sym.FIG_ELIPSE, yytext());
            }
          // fall through
          case 129: break;
          case 51:
            { return symbol(sym.INICIO, yytext());
            }
          // fall through
          case 130: break;
          case 52:
            { return symbol(sym.FIG_CIRCULO, yytext());
            }
          // fall through
          case 131: break;
          case 53:
            { return symbol(sym.COLOR_HEX, yytext());
            }
          // fall through
          case 132: break;
          case 54:
            { return symbol(sym.MOSTRAR, yytext());
            }
          // fall through
          case 133: break;
          case 55:
            { return symbol(sym.FONT_VERDANA, yytext());
            }
          // fall through
          case 134: break;
          case 56:
            { return symbol(sym.CONF_DEFAULT, yytext());
            }
          // fall through
          case 135: break;
          case 57:
            { return symbol(sym.ENTONCES, yytext());
            }
          // fall through
          case 136: break;
          case 58:
            { return symbol(sym.MIENTRAS, yytext());
            }
          // fall through
          case 137: break;
          case 59:
            { return symbol(sym.CONF_COLOR_SI, yytext());
            }
          // fall through
          case 138: break;
          case 60:
            { return symbol(sym.CONF_LETRA_SI, yytext());
            }
          // fall through
          case 139: break;
          case 61:
            { return symbol(sym.CONF_FIGURA_SI, yytext());
            }
          // fall through
          case 140: break;
          case 62:
            { return symbol(sym.FONT_COMIC, yytext());
            }
          // fall through
          case 141: break;
          case 63:
            { return symbol(sym.FIG_RECTANGULO, yytext());
            }
          // fall through
          case 142: break;
          case 64:
            { return symbol(sym.FINMIENTRAS, yytext());
            }
          // fall through
          case 143: break;
          case 65:
            { return symbol(sym.CONF_COLOR_BLOQUE, yytext());
            }
          // fall through
          case 144: break;
          case 66:
            { return symbol(sym.CONF_LETRA_BLOQUE, yytext());
            }
          // fall through
          case 145: break;
          case 67:
            { return symbol(sym.FIG_PARALELOGRAMO, yytext());
            }
          // fall through
          case 146: break;
          case 68:
            { return symbol(sym.CONF_FIGURA_BLOQUE, yytext());
            }
          // fall through
          case 147: break;
          case 69:
            { return symbol(sym.CONF_LETRA_SIZE_SI, yytext());
            }
          // fall through
          case 148: break;
          case 70:
            { return symbol(sym.CONF_COLOR_MIENTRAS, yytext());
            }
          // fall through
          case 149: break;
          case 71:
            { return symbol(sym.CONF_COLOR_TEXT_SI, yytext());
            }
          // fall through
          case 150: break;
          case 72:
            { return symbol(sym.CONF_LETRA_MIENTRAS, yytext());
            }
          // fall through
          case 151: break;
          case 73:
            { return symbol(sym.FONT_TIMES, yytext());
            }
          // fall through
          case 152: break;
          case 74:
            { return symbol(sym.CONF_FIGURA_MIENTRAS, yytext());
            }
          // fall through
          case 153: break;
          case 75:
            { return symbol(sym.CONF_LETRA_SIZE_BLOQUE, yytext());
            }
          // fall through
          case 154: break;
          case 76:
            { return symbol(sym.CONF_COLOR_TEXT_BLOQUE, yytext());
            }
          // fall through
          case 155: break;
          case 77:
            { return symbol(sym.CONF_LETRA_SIZE_MIENTRAS, yytext());
            }
          // fall through
          case 156: break;
          case 78:
            { return symbol(sym.CONF_COLOR_TEXT_MIENTRAS, yytext());
            }
          // fall through
          case 157: break;
          case 79:
            { return symbol(sym.FIG_REC_REDONDEADO, yytext());
            }
          // fall through
          case 158: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
