package com.example.generadordiagramas.analizador;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\123\000\002\002\004\000\002\002\005\000\002\003" +
    "\005\000\002\004\004\000\002\004\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\005\004\000" +
    "\002\005\003\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\010\006\000\002\010" +
    "\004\000\002\011\005\000\002\012\004\000\002\012\004" +
    "\000\002\013\004\000\002\027\003\000\002\027\004\000" +
    "\002\030\003\000\002\030\004\000\002\014\011\000\002" +
    "\015\011\000\002\016\005\000\002\016\005\000\002\016" +
    "\005\000\002\016\005\000\002\016\005\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\017\005\000" +
    "\002\017\005\000\002\017\005\000\002\017\005\000\002" +
    "\017\005\000\002\017\005\000\002\017\005\000\002\017" +
    "\005\000\002\017\004\000\002\017\005\000\002\020\003" +
    "\000\002\021\004\000\002\021\003\000\002\026\004\000" +
    "\002\026\003\000\002\026\002\000\002\023\007\000\002" +
    "\023\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003\000\002\024\003\000\002\024\003\000\002\024\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\025\003\000\002\022\005\000\002\022\004\000\002" +
    "\022\006\000\002\022\006\000\002\022\006\000\002\022" +
    "\005\000\002\022\006\000\002\022\006\000\002\022\006" +
    "\000\002\022\006\000\002\022\006\000\002\022\005\000" +
    "\002\022\006\000\002\022\006\000\002\022\006\000\002" +
    "\022\006\000\002\022\006\000\002\022\005\000\002\022" +
    "\006\000\002\022\006\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\266\000\004\004\006\001\002\000\004\002\270\001" +
    "\002\000\004\017\131\001\002\000\016\006\016\007\024" +
    "\011\023\013\012\014\017\076\020\001\002\000\020\005" +
    "\ufffb\006\ufffb\007\ufffb\011\ufffb\013\ufffb\014\ufffb\076\ufffb" +
    "\001\002\000\020\005\ufffc\006\ufffc\007\ufffc\011\ufffc\013" +
    "\ufffc\014\ufffc\076\ufffc\001\002\000\020\005\ufffa\006\ufffa" +
    "\007\ufffa\011\ufffa\013\ufffa\014\ufffa\076\ufffa\001\002\000" +
    "\014\070\054\074\035\075\033\076\027\077\130\001\002" +
    "\000\020\005\125\006\016\007\024\011\023\013\012\014" +
    "\017\076\020\001\002\000\020\005\ufffd\006\ufffd\007\ufffd" +
    "\011\ufffd\013\ufffd\014\ufffd\076\ufffd\001\002\000\024\005" +
    "\ufff6\006\ufff6\007\ufff6\011\ufff6\013\ufff6\014\ufff6\015\ufff6" +
    "\016\ufff6\076\ufff6\001\002\000\004\076\122\001\002\000" +
    "\004\076\121\001\002\000\004\067\117\001\002\000\024" +
    "\005\ufff7\006\ufff7\007\ufff7\011\ufff7\013\ufff7\014\ufff7\015" +
    "\ufff7\016\ufff7\076\ufff7\001\002\000\024\005\ufff4\006\ufff4" +
    "\007\ufff4\011\ufff4\013\ufff4\014\ufff4\015\ufff4\016\ufff4\076" +
    "\ufff4\001\002\000\004\070\106\001\002\000\004\070\026" +
    "\001\002\000\024\005\ufff5\006\ufff5\007\ufff5\011\ufff5\013" +
    "\ufff5\014\ufff5\015\ufff5\016\ufff5\076\ufff5\001\002\000\014" +
    "\066\030\070\034\074\035\075\033\076\027\001\002\000" +
    "\134\002\uffe0\003\uffe0\005\uffe0\006\uffe0\007\uffe0\011\uffe0" +
    "\013\uffe0\014\uffe0\015\uffe0\016\uffe0\020\uffe0\021\uffe0\022" +
    "\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0" +
    "\031\uffe0\032\uffe0\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037" +
    "\uffe0\052\uffe0\053\uffe0\054\uffe0\055\uffe0\056\uffe0\057\uffe0" +
    "\060\uffe0\061\uffe0\062\uffe0\063\uffe0\064\uffe0\065\uffe0\070" +
    "\uffe0\071\uffe0\072\uffe0\073\uffe0\074\uffe0\075\uffe0\076\uffe0" +
    "\001\002\000\014\066\030\070\034\074\035\075\033\076" +
    "\027\001\002\000\010\064\067\065\071\071\074\001\002" +
    "\000\026\052\046\053\041\054\044\055\047\056\040\057" +
    "\051\060\050\061\042\062\043\063\052\001\002\000\134" +
    "\002\uffe1\003\uffe1\005\uffe1\006\uffe1\007\uffe1\011\uffe1\013" +
    "\uffe1\014\uffe1\015\uffe1\016\uffe1\020\uffe1\021\uffe1\022\uffe1" +
    "\023\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031" +
    "\uffe1\032\uffe1\033\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1" +
    "\052\uffe1\053\uffe1\054\uffe1\055\uffe1\056\uffe1\057\uffe1\060" +
    "\uffe1\061\uffe1\062\uffe1\063\uffe1\064\uffe1\065\uffe1\070\uffe1" +
    "\071\uffe1\072\uffe1\073\uffe1\074\uffe1\075\uffe1\076\uffe1\001" +
    "\002\000\014\066\030\070\034\074\035\075\033\076\027" +
    "\001\002\000\134\002\uffe2\003\uffe2\005\uffe2\006\uffe2\007" +
    "\uffe2\011\uffe2\013\uffe2\014\uffe2\015\uffe2\016\uffe2\020\uffe2" +
    "\021\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027" +
    "\uffe2\030\uffe2\031\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2" +
    "\036\uffe2\037\uffe2\052\uffe2\053\uffe2\054\uffe2\055\uffe2\056" +
    "\uffe2\057\uffe2\060\uffe2\061\uffe2\062\uffe2\063\uffe2\064\uffe2" +
    "\065\uffe2\070\uffe2\071\uffe2\072\uffe2\073\uffe2\074\uffe2\075" +
    "\uffe2\076\uffe2\001\002\000\010\064\067\065\071\071\070" +
    "\001\002\000\030\052\046\053\041\054\044\055\047\056" +
    "\040\057\051\060\050\061\042\062\043\063\052\071\045" +
    "\001\002\000\012\070\054\074\035\075\033\076\027\001" +
    "\002\000\012\070\054\074\035\075\033\076\027\001\002" +
    "\000\012\070\054\074\035\075\033\076\027\001\002\000" +
    "\012\070\054\074\035\075\033\076\027\001\002\000\012" +
    "\070\054\074\035\075\033\076\027\001\002\000\134\002" +
    "\uffe3\003\uffe3\005\uffe3\006\uffe3\007\uffe3\011\uffe3\013\uffe3" +
    "\014\uffe3\015\uffe3\016\uffe3\020\uffe3\021\uffe3\022\uffe3\023" +
    "\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3" +
    "\032\uffe3\033\uffe3\034\uffe3\035\uffe3\036\uffe3\037\uffe3\052" +
    "\uffe3\053\uffe3\054\uffe3\055\uffe3\056\uffe3\057\uffe3\060\uffe3" +
    "\061\uffe3\062\uffe3\063\uffe3\064\uffe3\065\uffe3\070\uffe3\071" +
    "\uffe3\072\uffe3\073\uffe3\074\uffe3\075\uffe3\076\uffe3\001\002" +
    "\000\012\070\054\074\035\075\033\076\027\001\002\000" +
    "\012\070\054\074\035\075\033\076\027\001\002\000\012" +
    "\070\054\074\035\075\033\076\027\001\002\000\012\070" +
    "\054\074\035\075\033\076\027\001\002\000\012\070\054" +
    "\074\035\075\033\076\027\001\002\000\020\052\046\053" +
    "\041\054\044\055\047\064\uffda\065\uffda\071\uffda\001\002" +
    "\000\012\070\054\074\035\075\033\076\027\001\002\000" +
    "\014\052\046\053\041\054\044\055\047\071\045\001\002" +
    "\000\020\052\046\053\041\054\044\055\047\064\uffde\065" +
    "\uffde\071\uffde\001\002\000\020\052\046\053\041\054\044" +
    "\055\047\064\uffdd\065\uffdd\071\uffdd\001\002\000\134\002" +
    "\uffe4\003\uffe4\005\uffe4\006\uffe4\007\uffe4\011\uffe4\013\uffe4" +
    "\014\uffe4\015\uffe4\016\uffe4\020\uffe4\021\uffe4\022\uffe4\023" +
    "\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4" +
    "\032\uffe4\033\uffe4\034\uffe4\035\uffe4\036\uffe4\037\uffe4\052" +
    "\uffe4\053\uffe4\054\uffe4\055\uffe4\056\uffe4\057\uffe4\060\uffe4" +
    "\061\uffe4\062\uffe4\063\uffe4\064\uffe4\065\uffe4\070\uffe4\071" +
    "\uffe4\072\uffe4\073\uffe4\074\uffe4\075\uffe4\076\uffe4\001\002" +
    "\000\134\002\uffe7\003\uffe7\005\uffe7\006\uffe7\007\uffe7\011" +
    "\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7\020\uffe7\021\uffe7" +
    "\022\uffe7\023\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030" +
    "\uffe7\031\uffe7\032\uffe7\033\uffe7\034\uffe7\035\uffe7\036\uffe7" +
    "\037\uffe7\052\uffe7\053\uffe7\054\044\055\047\056\uffe7\057" +
    "\uffe7\060\uffe7\061\uffe7\062\uffe7\063\uffe7\064\uffe7\065\uffe7" +
    "\070\uffe7\071\uffe7\072\uffe7\073\uffe7\074\uffe7\075\uffe7\076" +
    "\uffe7\001\002\000\134\002\uffe5\003\uffe5\005\uffe5\006\uffe5" +
    "\007\uffe5\011\uffe5\013\uffe5\014\uffe5\015\uffe5\016\uffe5\020" +
    "\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026\uffe5" +
    "\027\uffe5\030\uffe5\031\uffe5\032\uffe5\033\uffe5\034\uffe5\035" +
    "\uffe5\036\uffe5\037\uffe5\052\uffe5\053\uffe5\054\uffe5\055\uffe5" +
    "\056\uffe5\057\uffe5\060\uffe5\061\uffe5\062\uffe5\063\uffe5\064" +
    "\uffe5\065\uffe5\070\uffe5\071\uffe5\072\uffe5\073\uffe5\074\uffe5" +
    "\075\uffe5\076\uffe5\001\002\000\020\052\046\053\041\054" +
    "\044\055\047\064\uffdb\065\uffdb\071\uffdb\001\002\000\020" +
    "\052\046\053\041\054\044\055\047\064\uffdc\065\uffdc\071" +
    "\uffdc\001\002\000\134\002\uffe6\003\uffe6\005\uffe6\006\uffe6" +
    "\007\uffe6\011\uffe6\013\uffe6\014\uffe6\015\uffe6\016\uffe6\020" +
    "\uffe6\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025\uffe6\026\uffe6" +
    "\027\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6\034\uffe6\035" +
    "\uffe6\036\uffe6\037\uffe6\052\uffe6\053\uffe6\054\044\055\047" +
    "\056\uffe6\057\uffe6\060\uffe6\061\uffe6\062\uffe6\063\uffe6\064" +
    "\uffe6\065\uffe6\070\uffe6\071\uffe6\072\uffe6\073\uffe6\074\uffe6" +
    "\075\uffe6\076\uffe6\001\002\000\020\052\046\053\041\054" +
    "\044\055\047\064\uffdf\065\uffdf\071\uffdf\001\002\000\014" +
    "\066\030\070\034\074\035\075\033\076\027\001\002\000" +
    "\010\064\uffd6\065\uffd6\071\uffd6\001\002\000\014\066\030" +
    "\070\034\074\035\075\033\076\027\001\002\000\010\064" +
    "\067\065\uffd8\071\uffd8\001\002\000\010\064\uffd9\065\uffd9" +
    "\071\uffd9\001\002\000\004\010\075\001\002\000\012\006" +
    "\016\013\012\014\017\076\020\001\002\000\020\005\ufff8" +
    "\006\ufff8\013\ufff8\014\ufff8\015\ufff8\016\ufff8\076\ufff8\001" +
    "\002\000\016\005\101\006\016\013\012\014\017\015\103" +
    "\076\020\001\002\000\020\005\ufff9\006\ufff9\013\ufff9\014" +
    "\ufff9\015\ufff9\016\ufff9\076\ufff9\001\002\000\004\007\104" +
    "\001\002\000\020\005\uffe9\006\uffe9\007\uffe9\011\uffe9\013" +
    "\uffe9\014\uffe9\076\uffe9\001\002\000\020\005\uffed\006\uffed" +
    "\007\uffed\011\uffed\013\uffed\014\uffed\076\uffed\001\002\000" +
    "\020\005\uffec\006\uffec\007\uffec\011\uffec\013\uffec\014\uffec" +
    "\076\uffec\001\002\000\010\064\uffd7\065\uffd7\071\uffd7\001" +
    "\002\000\014\066\030\070\034\074\035\075\033\076\027" +
    "\001\002\000\010\064\067\065\071\071\110\001\002\000" +
    "\004\012\111\001\002\000\012\006\016\013\012\014\017" +
    "\076\020\001\002\000\016\005\115\006\016\013\012\014" +
    "\017\016\114\076\020\001\002\000\020\005\uffe8\006\uffe8" +
    "\007\uffe8\011\uffe8\013\uffe8\014\uffe8\076\uffe8\001\002\000" +
    "\020\005\uffeb\006\uffeb\007\uffeb\011\uffeb\013\uffeb\014\uffeb" +
    "\076\uffeb\001\002\000\004\011\116\001\002\000\020\005" +
    "\uffea\006\uffea\007\uffea\011\uffea\013\uffea\014\uffea\076\uffea" +
    "\001\002\000\012\070\054\074\035\075\033\076\027\001" +
    "\002\000\034\005\ufff1\006\ufff1\007\ufff1\011\ufff1\013\ufff1" +
    "\014\ufff1\015\ufff1\016\ufff1\052\046\053\041\054\044\055" +
    "\047\076\ufff1\001\002\000\024\005\uffee\006\uffee\007\uffee" +
    "\011\uffee\013\uffee\014\uffee\015\uffee\016\uffee\076\uffee\001" +
    "\002\000\026\005\ufff2\006\ufff2\007\ufff2\011\ufff2\013\ufff2" +
    "\014\ufff2\015\ufff2\016\ufff2\067\123\076\ufff2\001\002\000" +
    "\012\070\054\074\035\075\033\076\027\001\002\000\034" +
    "\005\ufff3\006\ufff3\007\ufff3\011\ufff3\013\ufff3\014\ufff3\015" +
    "\ufff3\016\ufff3\052\046\053\041\054\044\055\047\076\ufff3" +
    "\001\002\000\004\017\uffff\001\002\000\020\005\ufffe\006" +
    "\ufffe\007\ufffe\011\ufffe\013\ufffe\014\ufffe\076\ufffe\001\002" +
    "\000\034\005\uffef\006\uffef\007\uffef\011\uffef\013\uffef\014" +
    "\uffef\015\uffef\016\uffef\052\046\053\041\054\044\055\047" +
    "\076\uffef\001\002\000\024\005\ufff0\006\ufff0\007\ufff0\011" +
    "\ufff0\013\ufff0\014\ufff0\015\ufff0\016\ufff0\076\ufff0\001\002" +
    "\000\044\003\145\020\140\021\150\022\135\023\142\024" +
    "\141\025\155\026\152\027\146\030\132\031\147\032\136" +
    "\033\143\034\133\035\137\036\134\037\154\001\002\000" +
    "\004\067\265\001\002\000\020\040\210\041\212\042\213" +
    "\043\206\044\214\045\215\067\261\001\002\000\004\067" +
    "\255\001\002\000\020\040\210\041\212\042\213\043\206" +
    "\044\214\045\215\067\251\001\002\000\004\067\245\001" +
    "\002\000\004\067\242\001\002\000\004\067\237\001\002" +
    "\000\004\067\234\001\002\000\004\067\225\001\002\000" +
    "\004\067\222\001\002\000\046\002\uffd5\003\145\020\140" +
    "\021\150\022\135\023\142\024\141\025\155\026\152\027" +
    "\146\030\132\031\147\032\136\033\143\034\133\035\137" +
    "\036\134\037\154\001\002\000\046\002\uffaf\003\uffaf\020" +
    "\uffaf\021\uffaf\022\uffaf\023\uffaf\024\uffaf\025\uffaf\026\uffaf" +
    "\027\uffaf\030\uffaf\031\uffaf\032\uffaf\033\uffaf\034\uffaf\035" +
    "\uffaf\036\uffaf\037\uffaf\001\002\000\020\040\210\041\212" +
    "\042\213\043\206\044\214\045\215\067\211\001\002\000" +
    "\004\067\203\001\002\000\004\067\200\001\002\000\004" +
    "\002\000\001\002\000\004\067\175\001\002\000\046\002" +
    "\uffd3\003\uffd3\020\uffd3\021\uffd3\022\uffd3\023\uffd3\024\uffd3" +
    "\025\uffd3\026\uffd3\027\uffd3\030\uffd3\031\uffd3\032\uffd3\033" +
    "\uffd3\034\uffd3\035\uffd3\036\uffd3\037\uffd3\001\002\000\014" +
    "\067\172\070\054\074\035\075\033\076\027\001\002\000" +
    "\004\067\156\001\002\000\014\070\054\074\035\075\033" +
    "\076\027\100\160\001\002\000\060\002\uffd0\003\uffd0\020" +
    "\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0" +
    "\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035" +
    "\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035\075\033" +
    "\076\027\001\002\000\060\002\uffce\003\uffce\020\uffce\021" +
    "\uffce\022\uffce\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce" +
    "\030\uffce\031\uffce\032\uffce\033\uffce\034\uffce\035\uffce\036" +
    "\uffce\037\uffce\070\uffce\072\uffce\074\uffce\075\uffce\076\uffce" +
    "\001\002\000\014\052\046\053\041\054\044\055\047\073" +
    "\162\001\002\000\012\070\054\074\035\075\033\076\027" +
    "\001\002\000\014\052\046\053\041\054\044\055\047\073" +
    "\164\001\002\000\012\070\054\074\035\075\033\076\027" +
    "\001\002\000\070\002\uffcf\003\uffcf\020\uffcf\021\uffcf\022" +
    "\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027\uffcf\030\uffcf" +
    "\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf\036\uffcf\037" +
    "\uffcf\052\046\053\041\054\044\055\047\070\uffcf\072\uffcf" +
    "\074\uffcf\075\uffcf\076\uffcf\001\002\000\046\002\uffbb\003" +
    "\uffbb\020\uffbb\021\uffbb\022\uffbb\023\uffbb\024\uffbb\025\uffbb" +
    "\026\uffbb\027\uffbb\030\uffbb\031\uffbb\032\uffbb\033\uffbb\034" +
    "\uffbb\035\uffbb\036\uffbb\037\uffbb\001\002\000\056\002\uffd1" +
    "\003\uffd1\020\uffd1\021\uffd1\022\uffd1\023\uffd1\024\uffd1\025" +
    "\uffd1\026\uffd1\027\uffd1\030\uffd1\031\uffd1\032\uffd1\033\uffd1" +
    "\034\uffd1\035\uffd1\036\uffd1\037\uffd1\052\046\053\041\054" +
    "\044\055\047\001\002\000\012\070\054\074\035\075\033" +
    "\076\027\001\002\000\056\002\uffd2\003\uffd2\020\uffd2\021" +
    "\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\026\uffd2\027\uffd2" +
    "\030\uffd2\031\uffd2\032\uffd2\033\uffd2\034\uffd2\035\uffd2\036" +
    "\uffd2\037\uffd2\052\046\053\041\054\044\055\047\001\002" +
    "\000\012\070\054\074\035\075\033\076\027\001\002\000" +
    "\056\002\uffc2\003\uffc2\020\uffc2\021\uffc2\022\uffc2\023\uffc2" +
    "\024\uffc2\025\uffc2\026\uffc2\027\uffc2\030\uffc2\031\uffc2\032" +
    "\uffc2\033\uffc2\034\uffc2\035\uffc2\036\uffc2\037\uffc2\052\046" +
    "\053\041\054\044\055\047\001\002\000\056\002\uffc3\003" +
    "\uffc3\020\uffc3\021\uffc3\022\uffc3\023\uffc3\024\uffc3\025\uffc3" +
    "\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\034" +
    "\uffc3\035\uffc3\036\uffc3\037\uffc3\052\046\053\041\054\044" +
    "\055\047\001\002\000\014\070\054\074\035\075\033\076" +
    "\027\100\160\001\002\000\060\002\uffd0\003\uffd0\020\uffd0" +
    "\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027" +
    "\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0" +
    "\036\uffd0\037\uffd0\070\054\072\170\074\035\075\033\076" +
    "\027\001\002\000\046\002\uffba\003\uffba\020\uffba\021\uffba" +
    "\022\uffba\023\uffba\024\uffba\025\uffba\026\uffba\027\uffba\030" +
    "\uffba\031\uffba\032\uffba\033\uffba\034\uffba\035\uffba\036\uffba" +
    "\037\uffba\001\002\000\014\070\054\074\035\075\033\076" +
    "\027\100\160\001\002\000\060\002\uffd0\003\uffd0\020\uffd0" +
    "\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027" +
    "\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0" +
    "\036\uffd0\037\uffd0\070\054\072\170\074\035\075\033\076" +
    "\027\001\002\000\046\002\uffc0\003\uffc0\020\uffc0\021\uffc0" +
    "\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0" +
    "\037\uffc0\001\002\000\012\070\054\074\035\075\033\076" +
    "\027\001\002\000\070\002\uffd0\003\uffd0\020\uffd0\021\uffd0" +
    "\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030" +
    "\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0" +
    "\037\uffd0\052\046\053\041\054\044\055\047\070\054\072" +
    "\170\074\035\075\033\076\027\001\002\000\046\002\uffb6" +
    "\003\uffb6\020\uffb6\021\uffb6\022\uffb6\023\uffb6\024\uffb6\025" +
    "\uffb6\026\uffb6\027\uffb6\030\uffb6\031\uffb6\032\uffb6\033\uffb6" +
    "\034\uffb6\035\uffb6\036\uffb6\037\uffb6\001\002\000\060\002" +
    "\uffca\003\uffca\020\uffca\021\uffca\022\uffca\023\uffca\024\uffca" +
    "\025\uffca\026\uffca\027\uffca\030\uffca\031\uffca\032\uffca\033" +
    "\uffca\034\uffca\035\uffca\036\uffca\037\uffca\070\uffca\072\uffca" +
    "\074\uffca\075\uffca\076\uffca\001\002\000\060\002\uffd0\003" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034" +
    "\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035" +
    "\075\033\076\027\001\002\000\060\002\uffcd\003\uffcd\020" +
    "\uffcd\021\uffcd\022\uffcd\023\uffcd\024\uffcd\025\uffcd\026\uffcd" +
    "\027\uffcd\030\uffcd\031\uffcd\032\uffcd\033\uffcd\034\uffcd\035" +
    "\uffcd\036\uffcd\037\uffcd\070\uffcd\072\uffcd\074\uffcd\075\uffcd" +
    "\076\uffcd\001\002\000\016\040\210\041\212\042\213\043" +
    "\206\044\214\045\215\001\002\000\060\002\uffcc\003\uffcc" +
    "\020\uffcc\021\uffcc\022\uffcc\023\uffcc\024\uffcc\025\uffcc\026" +
    "\uffcc\027\uffcc\030\uffcc\031\uffcc\032\uffcc\033\uffcc\034\uffcc" +
    "\035\uffcc\036\uffcc\037\uffcc\070\uffcc\072\uffcc\074\uffcc\075" +
    "\uffcc\076\uffcc\001\002\000\060\002\uffcb\003\uffcb\020\uffcb" +
    "\021\uffcb\022\uffcb\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027" +
    "\uffcb\030\uffcb\031\uffcb\032\uffcb\033\uffcb\034\uffcb\035\uffcb" +
    "\036\uffcb\037\uffcb\070\uffcb\072\uffcb\074\uffcb\075\uffcb\076" +
    "\uffcb\001\002\000\060\002\uffc9\003\uffc9\020\uffc9\021\uffc9" +
    "\022\uffc9\023\uffc9\024\uffc9\025\uffc9\026\uffc9\027\uffc9\030" +
    "\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\036\uffc9" +
    "\037\uffc9\070\uffc9\072\uffc9\074\uffc9\075\uffc9\076\uffc9\001" +
    "\002\000\060\002\uffc8\003\uffc8\020\uffc8\021\uffc8\022\uffc8" +
    "\023\uffc8\024\uffc8\025\uffc8\026\uffc8\027\uffc8\030\uffc8\031" +
    "\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8" +
    "\070\uffc8\072\uffc8\074\uffc8\075\uffc8\076\uffc8\001\002\000" +
    "\060\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0" +
    "\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032" +
    "\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054" +
    "\072\170\074\035\075\033\076\027\001\002\000\046\002" +
    "\uffb9\003\uffb9\020\uffb9\021\uffb9\022\uffb9\023\uffb9\024\uffb9" +
    "\025\uffb9\026\uffb9\027\uffb9\030\uffb9\031\uffb9\032\uffb9\033" +
    "\uffb9\034\uffb9\035\uffb9\036\uffb9\037\uffb9\001\002\000\046" +
    "\002\uffb8\003\uffb8\020\uffb8\021\uffb8\022\uffb8\023\uffb8\024" +
    "\uffb8\025\uffb8\026\uffb8\027\uffb8\030\uffb8\031\uffb8\032\uffb8" +
    "\033\uffb8\034\uffb8\035\uffb8\036\uffb8\037\uffb8\001\002\000" +
    "\046\002\uffd4\003\uffd4\020\uffd4\021\uffd4\022\uffd4\023\uffd4" +
    "\024\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032" +
    "\uffd4\033\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\001\002" +
    "\000\014\070\054\074\035\075\033\076\027\100\160\001" +
    "\002\000\060\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0" +
    "\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031" +
    "\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0" +
    "\070\054\072\170\074\035\075\033\076\027\001\002\000" +
    "\046\002\uffb4\003\uffb4\020\uffb4\021\uffb4\022\uffb4\023\uffb4" +
    "\024\uffb4\025\uffb4\026\uffb4\027\uffb4\030\uffb4\031\uffb4\032" +
    "\uffb4\033\uffb4\034\uffb4\035\uffb4\036\uffb4\037\uffb4\001\002" +
    "\000\012\046\230\047\231\050\232\051\226\001\002\000" +
    "\060\002\uffc4\003\uffc4\020\uffc4\021\uffc4\022\uffc4\023\uffc4" +
    "\024\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032" +
    "\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\070\uffc4" +
    "\072\uffc4\074\uffc4\075\uffc4\076\uffc4\001\002\000\060\002" +
    "\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0" +
    "\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033" +
    "\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170" +
    "\074\035\075\033\076\027\001\002\000\060\002\uffc7\003" +
    "\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7\024\uffc7\025\uffc7" +
    "\026\uffc7\027\uffc7\030\uffc7\031\uffc7\032\uffc7\033\uffc7\034" +
    "\uffc7\035\uffc7\036\uffc7\037\uffc7\070\uffc7\072\uffc7\074\uffc7" +
    "\075\uffc7\076\uffc7\001\002\000\060\002\uffc6\003\uffc6\020" +
    "\uffc6\021\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6" +
    "\027\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6\034\uffc6\035" +
    "\uffc6\036\uffc6\037\uffc6\070\uffc6\072\uffc6\074\uffc6\075\uffc6" +
    "\076\uffc6\001\002\000\060\002\uffc5\003\uffc5\020\uffc5\021" +
    "\uffc5\022\uffc5\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5" +
    "\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034\uffc5\035\uffc5\036" +
    "\uffc5\037\uffc5\070\uffc5\072\uffc5\074\uffc5\075\uffc5\076\uffc5" +
    "\001\002\000\046\002\uffbd\003\uffbd\020\uffbd\021\uffbd\022" +
    "\uffbd\023\uffbd\024\uffbd\025\uffbd\026\uffbd\027\uffbd\030\uffbd" +
    "\031\uffbd\032\uffbd\033\uffbd\034\uffbd\035\uffbd\036\uffbd\037" +
    "\uffbd\001\002\000\012\070\054\074\035\075\033\076\027" +
    "\001\002\000\070\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022" +
    "\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0" +
    "\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037" +
    "\uffd0\052\046\053\041\054\044\055\047\070\054\072\170" +
    "\074\035\075\033\076\027\001\002\000\046\002\uffbc\003" +
    "\uffbc\020\uffbc\021\uffbc\022\uffbc\023\uffbc\024\uffbc\025\uffbc" +
    "\026\uffbc\027\uffbc\030\uffbc\031\uffbc\032\uffbc\033\uffbc\034" +
    "\uffbc\035\uffbc\036\uffbc\037\uffbc\001\002\000\014\070\054" +
    "\074\035\075\033\076\027\100\160\001\002\000\060\002" +
    "\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0" +
    "\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033" +
    "\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170" +
    "\074\035\075\033\076\027\001\002\000\046\002\uffc1\003" +
    "\uffc1\020\uffc1\021\uffc1\022\uffc1\023\uffc1\024\uffc1\025\uffc1" +
    "\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\033\uffc1\034" +
    "\uffc1\035\uffc1\036\uffc1\037\uffc1\001\002\000\012\046\230" +
    "\047\231\050\232\051\226\001\002\000\060\002\uffd0\003" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034" +
    "\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035" +
    "\075\033\076\027\001\002\000\046\002\uffb1\003\uffb1\020" +
    "\uffb1\021\uffb1\022\uffb1\023\uffb1\024\uffb1\025\uffb1\026\uffb1" +
    "\027\uffb1\030\uffb1\031\uffb1\032\uffb1\033\uffb1\034\uffb1\035" +
    "\uffb1\036\uffb1\037\uffb1\001\002\000\014\070\054\074\035" +
    "\075\033\076\027\100\160\001\002\000\060\002\uffd0\003" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034" +
    "\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035" +
    "\075\033\076\027\001\002\000\046\002\uffb5\003\uffb5\020" +
    "\uffb5\021\uffb5\022\uffb5\023\uffb5\024\uffb5\025\uffb5\026\uffb5" +
    "\027\uffb5\030\uffb5\031\uffb5\032\uffb5\033\uffb5\034\uffb5\035" +
    "\uffb5\036\uffb5\037\uffb5\001\002\000\060\002\uffd0\003\uffd0" +
    "\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026" +
    "\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0" +
    "\035\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035\075" +
    "\033\076\027\001\002\000\016\040\210\041\212\042\213" +
    "\043\206\044\214\045\215\001\002\000\060\002\uffd0\003" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034" +
    "\uffd0\035\uffd0\036\uffd0\037\uffd0\070\054\072\170\074\035" +
    "\075\033\076\027\001\002\000\046\002\uffbf\003\uffbf\020" +
    "\uffbf\021\uffbf\022\uffbf\023\uffbf\024\uffbf\025\uffbf\026\uffbf" +
    "\027\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf\034\uffbf\035" +
    "\uffbf\036\uffbf\037\uffbf\001\002\000\046\002\uffbe\003\uffbe" +
    "\020\uffbe\021\uffbe\022\uffbe\023\uffbe\024\uffbe\025\uffbe\026" +
    "\uffbe\027\uffbe\030\uffbe\031\uffbe\032\uffbe\033\uffbe\034\uffbe" +
    "\035\uffbe\036\uffbe\037\uffbe\001\002\000\012\070\054\074" +
    "\035\075\033\076\027\001\002\000\070\002\uffd0\003\uffd0" +
    "\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026" +
    "\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0" +
    "\035\uffd0\036\uffd0\037\uffd0\052\046\053\041\054\044\055" +
    "\047\070\054\072\170\074\035\075\033\076\027\001\002" +
    "\000\046\002\uffb0\003\uffb0\020\uffb0\021\uffb0\022\uffb0\023" +
    "\uffb0\024\uffb0\025\uffb0\026\uffb0\027\uffb0\030\uffb0\031\uffb0" +
    "\032\uffb0\033\uffb0\034\uffb0\035\uffb0\036\uffb0\037\uffb0\001" +
    "\002\000\060\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0" +
    "\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031" +
    "\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0" +
    "\070\054\072\170\074\035\075\033\076\027\001\002\000" +
    "\016\040\210\041\212\042\213\043\206\044\214\045\215" +
    "\001\002\000\060\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022" +
    "\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0" +
    "\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037" +
    "\uffd0\070\054\072\170\074\035\075\033\076\027\001\002" +
    "\000\046\002\uffb3\003\uffb3\020\uffb3\021\uffb3\022\uffb3\023" +
    "\uffb3\024\uffb3\025\uffb3\026\uffb3\027\uffb3\030\uffb3\031\uffb3" +
    "\032\uffb3\033\uffb3\034\uffb3\035\uffb3\036\uffb3\037\uffb3\001" +
    "\002\000\046\002\uffb2\003\uffb2\020\uffb2\021\uffb2\022\uffb2" +
    "\023\uffb2\024\uffb2\025\uffb2\026\uffb2\027\uffb2\030\uffb2\031" +
    "\uffb2\032\uffb2\033\uffb2\034\uffb2\035\uffb2\036\uffb2\037\uffb2" +
    "\001\002\000\012\046\230\047\231\050\232\051\226\001" +
    "\002\000\060\002\uffd0\003\uffd0\020\uffd0\021\uffd0\022\uffd0" +
    "\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031" +
    "\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0" +
    "\070\054\072\170\074\035\075\033\076\027\001\002\000" +
    "\046\002\uffb7\003\uffb7\020\uffb7\021\uffb7\022\uffb7\023\uffb7" +
    "\024\uffb7\025\uffb7\026\uffb7\027\uffb7\030\uffb7\031\uffb7\032" +
    "\uffb7\033\uffb7\034\uffb7\035\uffb7\036\uffb7\037\uffb7\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\266\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\004\012\006\013\007\007" +
    "\010\020\011\014\012\024\013\021\014\006\015\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\016\126\001\001\000\022\006\125\007\007\010" +
    "\020\011\014\012\024\013\021\014\006\015\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\031\017\030\001\001\000\002\001\001" +
    "\000\006\016\031\017\104\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\016\036\017\035" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\065\001\001\000\004\016\064\001\001" +
    "\000\004\016\063\001\001\000\004\016\062\001\001\000" +
    "\004\016\061\001\001\000\002\001\001\000\004\016\060" +
    "\001\001\000\004\016\057\001\001\000\004\016\056\001" +
    "\001\000\004\016\055\001\001\000\004\016\052\001\001" +
    "\000\002\001\001\000\004\016\054\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\016\031\017\072\001\001\000\002\001\001\000\006\016" +
    "\031\017\071\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\005\076\007\075\010\020\011" +
    "\014\012\024\013\021\001\001\000\002\001\001\000\016" +
    "\007\077\010\020\011\014\012\024\013\021\027\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\016\031\017\106\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\005\111\007\075\010\020\011\014\012" +
    "\024\013\021\001\001\000\016\007\077\010\020\011\014" +
    "\012\024\013\021\030\112\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\117\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\123\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\150\021\143\022\152\001\001" +
    "\000\002\001\001\000\004\024\257\001\001\000\002\001" +
    "\001\000\004\024\247\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\220\001\001\000\002" +
    "\001\001\000\004\024\206\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\172\001\001\000\002\001\001\000" +
    "\006\016\160\023\156\001\001\000\006\016\166\026\165" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\162\001\001\000\002\001\001\000\004\016\164\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\170\001\001\000\002\001\001\000\004\016\173" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\016" +
    "\160\023\175\001\001\000\006\016\166\026\176\001\001" +
    "\000\002\001\001\000\006\016\160\023\200\001\001\000" +
    "\006\016\166\026\201\001\001\000\002\001\001\000\004" +
    "\016\203\001\001\000\006\016\166\026\204\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\016\166\026\217" +
    "\001\001\000\002\001\001\000\004\024\215\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\016\166\026\216\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\016\160" +
    "\023\222\001\001\000\006\016\166\026\223\001\001\000" +
    "\002\001\001\000\004\025\226\001\001\000\002\001\001" +
    "\000\006\016\166\026\232\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\234\001\001\000\006\016\166\026\235\001\001\000" +
    "\002\001\001\000\006\016\160\023\237\001\001\000\006" +
    "\016\166\026\240\001\001\000\002\001\001\000\004\025" +
    "\242\001\001\000\006\016\166\026\243\001\001\000\002" +
    "\001\001\000\006\016\160\023\245\001\001\000\006\016" +
    "\166\026\246\001\001\000\002\001\001\000\006\016\166" +
    "\026\253\001\001\000\004\024\251\001\001\000\006\016" +
    "\166\026\252\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\016\255\001\001\000\006\016\166\026\256\001" +
    "\001\000\002\001\001\000\006\016\166\026\263\001\001" +
    "\000\004\024\261\001\001\000\006\016\166\026\262\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\025\265" +
    "\001\001\000\006\016\166\026\266\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static class ErrorSintactico
    {
        public String lexema;
        public int linea;
        public int columna;
        public String descripcion;

        public ErrorSintactico(String lexema, int linea, int columna, String descripcion)
        {
            this.lexema = lexema;
            this.linea = linea;
            this.columna = columna;
            this.descripcion = descripcion;
        }
    }
    public ArrayList<ErrorSintactico> listaErrores = new ArrayList<>();
    @Override
    public void syntax_error(Symbol s)
    {
        String lexema = s.value != null ? s.value.toString() : "Token desconocido";
        listaErrores.add(new ErrorSintactico(lexema, s.left, s.right, "Se esperaba otro token"));
        System.err.println("Error Sintáctico: " + lexema + " en línea " + s.left + " columna " + s.right);
    }
    @Override
    public void unrecovered_syntax_error(Symbol s) throws Exception
    {
        String lexema = s.value != null ? s.value.toString() : "Token desconocido";
        listaErrores.add(new ErrorSintactico(lexema, s.left, s.right, "Error sintáctico irrecuperable"));
        System.err.println("Error Sintáctico Irrecuperable: " + lexema + " en línea " + s.left + " columna " + s.right);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> start_val = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= seccion_algoritmo SEPARADOR seccion_configuracion 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<FiguraDiagrama> lista = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // seccion_algoritmo ::= INICIO instrucciones FIN 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> lista = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        ArrayList<FiguraDiagrama> diagrama = new ArrayList<>();
        diagrama.add(new FiguraDiagrama("INICIO", "INICIO"));
        diagrama.addAll(lista);
        diagrama.add(new FiguraDiagrama("FIN", "FIN"));
        RESULT = diagrama;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_algoritmo",1, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instrucciones ::= instrucciones instruccion 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> lista = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama inst = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		
        lista.add(inst);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",2, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucciones ::= instruccion 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama inst = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList<FiguraDiagrama> lista = new ArrayList<>();
        lista.add(inst);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",2, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= instruccion_simple 
            {
              FiguraDiagrama RESULT =null;
		int ileft = ((Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama i = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= condicional 
            {
              FiguraDiagrama RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama c = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= ciclo 
            {
              FiguraDiagrama RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama c = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bloque_simple ::= bloque_simple instruccion_simple 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> lista = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama inst = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		
        lista.add(inst);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_simple",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bloque_simple ::= instruccion_simple 
            {
              ArrayList<FiguraDiagrama> RESULT =null;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama inst = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList<FiguraDiagrama> lista = new ArrayList<>();
        lista.add(inst);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_simple",3, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion_simple ::= declaracion 
            {
              FiguraDiagrama RESULT =null;
		int dleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama d = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion_simple ::= asignacion 
            {
              FiguraDiagrama RESULT =null;
		int aleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama a = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion_simple ::= mostrar 
            {
              FiguraDiagrama RESULT =null;
		int mleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama m = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = m; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion_simple ::= leer 
            {
              FiguraDiagrama RESULT =null;
		int lleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((Symbol)CUP$Parser$stack.peek()).right;
		FiguraDiagrama l = (FiguraDiagrama)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracion ::= VAR ID IGUAL_ASIG expr_aritmetica 
            {
              FiguraDiagrama RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("PROCESO", "VAR " + id + " = " + e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion ::= VAR ID 
            {
              FiguraDiagrama RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("PROCESO", "VAR " + id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // asignacion ::= ID IGUAL_ASIG expr_aritmetica 
            {
              FiguraDiagrama RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("PROCESO", id + " = " + e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // mostrar ::= MOSTRAR CADENA 
            {
              FiguraDiagrama RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("IO", "MOSTRAR " + c); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mostrar",8, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // mostrar ::= MOSTRAR expr_aritmetica 
            {
              FiguraDiagrama RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("IO", "MOSTRAR " + e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mostrar",8, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // leer ::= LEER ID 
            {
              FiguraDiagrama RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FiguraDiagrama("IO", "LEER " + id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("leer",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // cierre_si ::= FINSI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cierre_si",21, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // cierre_si ::= FIN SI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cierre_si",21, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // cierre_mientras ::= FINMIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cierre_mientras",22, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cierre_mientras ::= FIN MIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cierre_mientras",22, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condicional ::= SI PAR_IZQ condicion PAR_DER ENTONCES bloque_simple cierre_si 
            {
              FiguraDiagrama RESULT =null;
		int condleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int condright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String cond = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bloqueleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bloqueright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> bloque = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        FiguraDiagrama nodoSi = new FiguraDiagrama("CONDICION", cond);
        nodoSi.bloqueInterno = bloque;
        RESULT = nodoSi;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicional",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ciclo ::= MIENTRAS PAR_IZQ condicion PAR_DER HACER bloque_simple cierre_mientras 
            {
              FiguraDiagrama RESULT =null;
		int condleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int condright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String cond = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bloqueleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bloqueright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<FiguraDiagrama> bloque = (ArrayList<FiguraDiagrama>)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        FiguraDiagrama nodoMientras = new FiguraDiagrama("CONDICION", "MIENTRAS " + cond);
        nodoMientras.bloqueInterno = bloque;
        RESULT = nodoMientras;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ciclo",11, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr_aritmetica ::= expr_aritmetica MAS expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " + " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr_aritmetica ::= expr_aritmetica MENOS expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " - " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr_aritmetica ::= expr_aritmetica POR expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " * " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr_aritmetica ::= expr_aritmetica DIV expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " / " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr_aritmetica ::= PAR_IZQ expr_aritmetica PAR_DER 
            {
              String RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + e + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr_aritmetica ::= ENTERO 
            {
              String RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr_aritmetica ::= DECIMAL 
            {
              String RESULT =null;
		int dleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr_aritmetica ::= ID 
            {
              String RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = id; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_aritmetica",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= expr_aritmetica IGUALDAD expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " == " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= expr_aritmetica DIFERENTE expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " != " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion ::= expr_aritmetica MAYOR expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " > " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion ::= expr_aritmetica MENOR expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " < " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion ::= expr_aritmetica MAYOR_IGUAL expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " >= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= expr_aritmetica MENOR_IGUAL expr_aritmetica 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " <= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicion ::= condicion AND condicion 
            {
              String RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String c2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " && " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condicion ::= condicion OR condicion 
            {
              String RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String c2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " || " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condicion ::= NOT condicion 
            {
              String RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = "!" + c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condicion ::= PAR_IZQ condicion PAR_DER 
            {
              String RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String c = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + c + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // seccion_configuracion ::= configuraciones 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_configuracion",14, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // configuraciones ::= configuraciones configuracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuraciones",15, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // configuraciones ::= configuracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuraciones",15, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // indice_opt ::= PIPE expr_aritmetica 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("indice_opt",20, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // indice_opt ::= expr_aritmetica 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("indice_opt",20, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // indice_opt ::= 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("indice_opt",20, ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr_color ::= expr_aritmetica COMA expr_aritmetica COMA expr_aritmetica 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_color",17, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr_color ::= COLOR_HEX 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_color",17, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // figura ::= FIG_ELIPSE 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // figura ::= FIG_CIRCULO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // figura ::= FIG_PARALELOGRAMO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // figura ::= FIG_RECTANGULO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // figura ::= FIG_ROMBO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // figura ::= FIG_REC_REDONDEADO 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",18, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // fuente ::= FONT_ARIAL 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente",19, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // fuente ::= FONT_TIMES 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente",19, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // fuente ::= FONT_COMIC 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente",19, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // fuente ::= FONT_VERDANA 
            {
              String RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente",19, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // configuracion ::= CONF_DEFAULT IGUAL_ASIG expr_aritmetica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // configuracion ::= CONF_DEFAULT expr_aritmetica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // configuracion ::= CONF_COLOR_TEXT_SI IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // configuracion ::= CONF_COLOR_SI IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // configuracion ::= CONF_FIGURA_SI IGUAL_ASIG figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // configuracion ::= CONF_FIGURA_SI figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // configuracion ::= CONF_LETRA_SI IGUAL_ASIG fuente indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // configuracion ::= CONF_LETRA_SIZE_SI IGUAL_ASIG expr_aritmetica indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // configuracion ::= CONF_COLOR_TEXT_MIENTRAS IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // configuracion ::= CONF_COLOR_MIENTRAS IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // configuracion ::= CONF_FIGURA_MIENTRAS IGUAL_ASIG figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // configuracion ::= CONF_FIGURA_MIENTRAS figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // configuracion ::= CONF_LETRA_MIENTRAS IGUAL_ASIG fuente indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // configuracion ::= CONF_LETRA_SIZE_MIENTRAS IGUAL_ASIG expr_aritmetica indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // configuracion ::= CONF_COLOR_TEXT_BLOQUE IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // configuracion ::= CONF_COLOR_BLOQUE IGUAL_ASIG expr_color indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // configuracion ::= CONF_FIGURA_BLOQUE IGUAL_ASIG figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // configuracion ::= CONF_FIGURA_BLOQUE figura indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // configuracion ::= CONF_LETRA_BLOQUE IGUAL_ASIG fuente indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // configuracion ::= CONF_LETRA_SIZE_BLOQUE IGUAL_ASIG expr_aritmetica indice_opt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // configuracion ::= error 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",16, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
