// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

import java_cup.runtime.*;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\1\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\0\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\12\21\2\0"+
    "\1\22\1\23\1\24\2\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\2\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\36\1\54\4\0\1\55\1\0"+
    "\6\56\24\36\1\0\1\57\10\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\2\2\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\16\17\1\20\1\21\1\0\1\22\1\2"+
    "\4\0\1\23\1\0\1\24\1\25\1\26\17\17\1\27"+
    "\3\17\1\30\4\0\1\31\5\17\1\32\12\17\1\33"+
    "\1\17\1\34\3\0\12\17\1\35\7\17\3\0\1\36"+
    "\5\17\1\37\1\17\1\40\5\17\1\41\2\17\3\0"+
    "\2\17\1\42\3\17\1\43\6\17\3\0\1\44\3\17"+
    "\1\45\1\17\1\46\3\17\1\47\10\0\1\17\1\50"+
    "\1\17\1\51\3\17\2\0\1\52\6\0\1\53\5\17"+
    "\5\0\1\54\3\0\1\55\2\17\1\56\1\17\10\0"+
    "\1\57\3\17\10\0\3\17\1\60\4\0\1\61\4\0"+
    "\1\62\2\17\4\0\1\63\4\0\1\64\2\17\1\65"+
    "\2\0\1\66\1\0\1\67\2\0\1\17\1\70\2\0"+
    "\1\71\2\0\1\17\4\0\1\17\2\0\1\72\1\0"+
    "\1\17\1\73\2\0\1\17\1\0\1\74\1\17\1\75"+
    "\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[289];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\60\0\u0180"+
    "\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0300"+
    "\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420\0\u0450\0\u0480"+
    "\0\u04b0\0\u04e0\0\60\0\300\0\60\0\60\0\u0510\0\u0540"+
    "\0\u0570\0\u05a0\0\60\0\u05d0\0\60\0\60\0\60\0\u0600"+
    "\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780"+
    "\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u0270\0\u08d0"+
    "\0\u0900\0\u0930\0\60\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u05d0"+
    "\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70"+
    "\0\u0ba0\0\u0bd0\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0270\0\u0d20\0\60\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\u0e10"+
    "\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u0f90"+
    "\0\u0270\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0"+
    "\0\u1110\0\u1140\0\u1170\0\u0270\0\u11a0\0\u11d0\0\u1200\0\u1230"+
    "\0\u1260\0\u0270\0\u1290\0\u0270\0\u12c0\0\u12f0\0\u1320\0\u1350"+
    "\0\u1380\0\u0270\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\u14a0"+
    "\0\u14d0\0\u0270\0\u1500\0\u1530\0\u1560\0\u0270\0\u1590\0\u15c0"+
    "\0\u15f0\0\u1620\0\u1650\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u0270"+
    "\0\u1740\0\u1770\0\u17a0\0\u0270\0\u17d0\0\u0270\0\u1800\0\u1830"+
    "\0\u1860\0\u0270\0\u1890\0\u18c0\0\u18f0\0\u1920\0\u1950\0\u1980"+
    "\0\u19b0\0\u19e0\0\u1a10\0\u0270\0\u1a40\0\u0270\0\u1a70\0\u1aa0"+
    "\0\u1ad0\0\u1b00\0\u1b30\0\60\0\u1b60\0\u1b90\0\u1bc0\0\u1bf0"+
    "\0\u1c20\0\u1c50\0\u1c80\0\u1cb0\0\u1ce0\0\u1d10\0\u1d40\0\u1d70"+
    "\0\u1da0\0\u1dd0\0\u1e00\0\u1e30\0\u1e60\0\60\0\u1e90\0\u1ec0"+
    "\0\u1ef0\0\u0270\0\u1f20\0\u1f50\0\u1f80\0\u1fb0\0\u1fe0\0\u2010"+
    "\0\u2040\0\u2070\0\u20a0\0\u20d0\0\u2100\0\u2130\0\u0270\0\u2160"+
    "\0\u2190\0\u21c0\0\u21f0\0\u2220\0\u2250\0\u2280\0\u22b0\0\u22e0"+
    "\0\u2310\0\u2340\0\u2370\0\u23a0\0\u23d0\0\60\0\u2400\0\u2430"+
    "\0\u2460\0\u2490\0\60\0\u24c0\0\u24f0\0\u2520\0\u2550\0\u0270"+
    "\0\u2580\0\u25b0\0\u25e0\0\u2610\0\u2640\0\u2670\0\60\0\u26a0"+
    "\0\u26d0\0\u2700\0\u2730\0\60\0\u2760\0\u2790\0\60\0\u27c0"+
    "\0\u27f0\0\60\0\u2820\0\60\0\u2850\0\u2880\0\u28b0\0\u0270"+
    "\0\u28e0\0\u2910\0\60\0\u2940\0\u2970\0\u29a0\0\u29d0\0\u2a00"+
    "\0\u2a30\0\u2a60\0\u2a90\0\u2ac0\0\u2af0\0\60\0\u2b20\0\u2b50"+
    "\0\60\0\u2b80\0\u2bb0\0\u2be0\0\u2c10\0\60\0\u2c40\0\60"+
    "\0\u0270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[289];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\25"+
    "\1\27\1\30\1\25\1\31\1\32\1\25\1\33\1\34"+
    "\2\25\1\35\1\25\1\36\1\37\1\40\1\25\1\41"+
    "\5\25\1\42\61\0\2\3\100\0\1\43\34\0\5\44"+
    "\1\45\52\44\2\6\1\46\55\6\7\0\1\47\17\0"+
    "\1\50\2\0\1\51\4\0\1\52\30\0\1\53\66\0"+
    "\1\54\1\0\1\20\61\0\1\55\57\0\1\56\57\0"+
    "\1\57\55\0\1\25\3\0\20\25\1\60\11\25\22\0"+
    "\1\25\3\0\32\25\22\0\1\25\3\0\10\25\1\61"+
    "\4\25\1\62\14\25\22\0\1\25\3\0\12\25\1\63"+
    "\1\25\1\64\15\25\22\0\1\25\3\0\10\25\1\65"+
    "\21\25\22\0\1\66\3\0\1\67\5\66\23\25\1\66"+
    "\22\0\1\25\3\0\14\25\1\70\15\25\22\0\1\25"+
    "\3\0\4\25\1\71\25\25\22\0\1\25\3\0\10\25"+
    "\1\72\4\25\1\73\14\25\22\0\1\25\3\0\1\74"+
    "\31\25\22\0\1\25\3\0\4\25\1\75\10\25\1\76"+
    "\14\25\22\0\1\25\3\0\10\25\1\77\21\25\22\0"+
    "\1\25\3\0\10\25\1\100\21\25\22\0\1\25\3\0"+
    "\1\101\3\25\1\102\25\25\60\0\1\103\7\0\1\104"+
    "\112\0\1\105\52\0\1\106\53\0\1\107\47\0\1\110"+
    "\57\0\1\25\3\0\10\25\1\111\21\25\22\0\1\25"+
    "\3\0\20\25\1\112\11\25\22\0\1\25\3\0\13\25"+
    "\1\113\16\25\22\0\1\25\3\0\10\25\1\114\21\25"+
    "\22\0\1\25\3\0\22\25\1\115\7\25\22\0\1\25"+
    "\3\0\14\25\1\116\15\25\22\0\1\117\3\0\6\117"+
    "\23\25\1\117\22\0\1\117\3\0\2\117\1\120\3\117"+
    "\23\25\1\117\22\0\1\25\3\0\10\25\1\121\21\25"+
    "\22\0\1\25\3\0\4\25\1\122\25\25\22\0\1\25"+
    "\3\0\4\25\1\123\25\25\22\0\1\25\3\0\21\25"+
    "\1\124\10\25\22\0\1\25\3\0\20\25\1\125\11\25"+
    "\22\0\1\25\3\0\2\25\1\126\27\25\22\0\1\25"+
    "\3\0\13\25\1\127\16\25\22\0\1\25\3\0\13\25"+
    "\1\130\16\25\22\0\1\25\3\0\20\25\1\131\11\25"+
    "\22\0\1\25\3\0\20\25\1\132\11\25\10\0\1\133"+
    "\107\0\1\134\53\0\1\135\73\0\1\136\31\0\1\25"+
    "\3\0\1\137\31\25\22\0\1\25\3\0\2\25\1\140"+
    "\27\25\22\0\1\25\3\0\10\25\1\141\21\25\22\0"+
    "\1\25\3\0\16\25\1\142\13\25\22\0\1\25\3\0"+
    "\15\25\1\143\14\25\22\0\1\25\3\0\13\25\1\144"+
    "\5\25\1\145\10\25\22\0\1\146\3\0\6\146\23\25"+
    "\1\146\22\0\1\146\3\0\4\146\1\147\1\146\23\25"+
    "\1\146\22\0\1\25\3\0\2\25\1\150\27\25\22\0"+
    "\1\25\3\0\20\25\1\151\11\25\22\0\1\25\3\0"+
    "\14\25\1\152\15\25\22\0\1\25\3\0\22\25\1\153"+
    "\7\25\22\0\1\25\3\0\1\154\31\25\22\0\1\25"+
    "\3\0\22\25\1\155\7\25\22\0\1\25\3\0\1\25"+
    "\1\156\30\25\22\0\1\25\3\0\4\25\1\157\25\25"+
    "\22\0\1\25\3\0\3\25\1\160\26\25\43\0\1\161"+
    "\65\0\1\162\54\0\1\163\33\0\1\25\3\0\12\25"+
    "\1\164\17\25\22\0\1\25\3\0\23\25\1\165\6\25"+
    "\22\0\1\25\3\0\2\25\1\166\27\25\22\0\1\25"+
    "\3\0\21\25\1\167\10\25\22\0\1\25\3\0\14\25"+
    "\1\170\15\25\22\0\1\25\3\0\10\25\1\171\21\25"+
    "\22\0\1\25\3\0\10\25\1\172\21\25\22\0\1\173"+
    "\3\0\6\173\23\25\1\173\22\0\1\173\3\0\6\173"+
    "\12\25\1\174\10\25\1\173\22\0\1\25\3\0\10\25"+
    "\1\175\21\25\22\0\1\25\3\0\22\25\1\176\7\25"+
    "\22\0\1\25\3\0\20\25\1\177\11\25\22\0\1\25"+
    "\3\0\12\25\1\200\17\25\22\0\1\25\3\0\1\201"+
    "\31\25\22\0\1\25\3\0\15\25\1\202\14\25\22\0"+
    "\1\25\3\0\21\25\1\203\10\25\22\0\1\25\3\0"+
    "\1\204\31\25\46\0\1\205\57\0\1\206\37\0\1\207"+
    "\53\0\1\25\3\0\12\25\1\210\17\25\22\0\1\25"+
    "\3\0\30\25\1\211\1\25\22\0\1\25\3\0\4\25"+
    "\1\212\25\25\22\0\1\25\3\0\2\25\1\213\27\25"+
    "\22\0\1\25\3\0\4\25\1\214\25\25\22\0\1\215"+
    "\3\0\6\215\23\25\1\215\22\0\1\25\3\0\15\25"+
    "\1\216\14\25\22\0\1\25\3\0\20\25\1\217\11\25"+
    "\22\0\1\25\3\0\1\220\31\25\22\0\1\25\3\0"+
    "\4\25\1\221\25\25\22\0\1\25\3\0\14\25\1\222"+
    "\15\25\22\0\1\25\3\0\30\25\1\223\1\25\22\0"+
    "\1\25\3\0\14\25\1\224\15\25\56\0\1\225\27\0"+
    "\1\226\107\0\1\227\23\0\1\25\3\0\15\25\1\230"+
    "\14\25\22\0\1\25\3\0\21\25\1\231\10\25\22\0"+
    "\1\25\3\0\4\25\1\232\25\25\22\0\1\25\3\0"+
    "\14\25\1\233\15\25\22\0\1\234\3\0\6\234\23\25"+
    "\1\234\22\0\1\25\3\0\1\235\31\25\22\0\1\25"+
    "\3\0\20\25\1\236\11\25\22\0\1\25\3\0\12\25"+
    "\1\237\17\25\22\0\1\25\3\0\6\25\1\240\23\25"+
    "\22\0\1\25\3\0\14\25\1\241\15\25\22\0\1\25"+
    "\3\0\1\242\31\25\27\0\1\243\11\0\1\244\5\0"+
    "\1\245\1\246\65\0\1\247\30\0\1\250\11\0\1\251"+
    "\5\0\1\252\32\0\1\25\3\0\1\253\31\25\22\0"+
    "\1\25\3\0\21\25\1\254\10\25\22\0\1\25\3\0"+
    "\22\25\1\255\7\25\22\0\1\25\3\0\21\25\1\256"+
    "\10\25\22\0\1\25\3\0\15\25\1\257\14\25\22\0"+
    "\1\25\3\0\23\25\1\260\6\25\22\0\1\25\3\0"+
    "\4\25\1\261\25\25\40\0\1\262\55\0\1\263\57\0"+
    "\1\264\53\0\1\265\54\0\1\266\11\0\1\267\5\0"+
    "\1\270\50\0\1\271\55\0\1\272\57\0\1\273\43\0"+
    "\1\25\3\0\14\25\1\274\15\25\22\0\1\25\3\0"+
    "\20\25\1\275\11\25\22\0\1\25\3\0\6\25\1\276"+
    "\23\25\22\0\1\25\3\0\12\25\1\277\17\25\22\0"+
    "\1\25\3\0\25\25\1\300\4\25\43\0\1\301\46\0"+
    "\1\302\101\0\1\303\43\0\1\304\55\0\1\305\57\0"+
    "\1\306\64\0\1\307\46\0\1\310\102\0\1\311\24\0"+
    "\1\25\3\0\21\25\1\312\10\25\22\0\1\25\3\0"+
    "\1\313\31\25\22\0\1\25\3\0\20\25\1\314\11\25"+
    "\22\0\1\25\3\0\15\25\1\315\14\25\22\0\1\25"+
    "\3\0\30\25\1\316\1\25\45\0\1\317\54\0\1\320"+
    "\65\0\1\321\52\0\1\322\46\0\1\323\72\0\1\324"+
    "\54\0\1\325\47\0\1\326\47\0\1\25\3\0\21\25"+
    "\1\327\10\25\22\0\1\25\3\0\1\330\31\25\22\0"+
    "\1\25\3\0\30\25\1\331\1\25\22\0\1\25\3\0"+
    "\20\25\1\332\11\25\51\0\1\333\56\0\1\334\52\0"+
    "\1\335\61\0\1\336\54\0\1\337\66\0\1\340\56\0"+
    "\1\341\65\0\1\342\23\0\1\25\3\0\13\25\1\343"+
    "\16\25\22\0\1\25\3\0\20\25\1\344\11\25\22\0"+
    "\1\25\3\0\15\25\1\345\14\25\32\0\1\346\73\0"+
    "\1\347\67\0\1\350\52\0\1\351\56\0\1\352\41\0"+
    "\1\353\73\0\1\354\40\0\1\355\11\0\1\356\5\0"+
    "\1\357\32\0\1\25\3\0\15\25\1\360\14\25\22\0"+
    "\1\25\3\0\4\25\1\361\25\25\22\0\1\25\3\0"+
    "\13\25\1\362\16\25\26\0\1\363\60\0\1\364\11\0"+
    "\1\365\5\0\1\366\42\0\1\367\73\0\1\370\37\0"+
    "\1\371\71\0\1\372\55\0\1\373\57\0\1\374\43\0"+
    "\1\25\3\0\3\25\1\375\26\25\22\0\1\25\3\0"+
    "\1\376\31\25\47\0\1\377\50\0\1\u0100\55\0\1\u0101"+
    "\57\0\1\u0102\47\0\1\u0103\100\0\1\u0104\53\0\1\u0105"+
    "\46\0\1\u0106\47\0\1\25\3\0\15\25\1\u0107\14\25"+
    "\22\0\1\25\3\0\14\25\1\u0108\15\25\43\0\1\u0109"+
    "\46\0\1\u010a\74\0\1\u010b\55\0\1\u010c\54\0\1\u010d"+
    "\37\0\1\25\3\0\14\25\1\u010e\15\25\45\0\1\u010f"+
    "\54\0\1\u0110\66\0\1\u0111\56\0\1\u0112\31\0\1\25"+
    "\3\0\3\25\1\u0113\26\25\51\0\1\u0114\56\0\1\u0115"+
    "\41\0\1\u0116\73\0\1\u0117\33\0\1\25\3\0\4\25"+
    "\1\u0118\25\25\32\0\1\u0119\73\0\1\u011a\37\0\1\u011b"+
    "\53\0\1\25\3\0\1\u011c\31\25\26\0\1\u011d\100\0"+
    "\1\u011e\32\0\1\25\3\0\3\25\1\u011f\26\25\47\0"+
    "\1\u0120\32\0\1\25\3\0\15\25\1\u0121\14\25\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11376];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\7\11\23\1\1\11\1\0\2\11"+
    "\4\0\1\11\1\0\3\11\23\1\1\11\4\0\23\1"+
    "\1\11\3\0\22\1\3\0\21\1\3\0\15\1\3\0"+
    "\13\1\10\0\7\1\2\0\1\11\6\0\6\1\5\0"+
    "\1\11\3\0\5\1\10\0\4\1\10\0\3\1\1\11"+
    "\4\0\1\11\4\0\3\1\4\0\1\11\4\0\1\11"+
    "\2\1\1\11\2\0\1\11\1\0\1\11\2\0\2\1"+
    "\2\0\1\11\2\0\1\1\4\0\1\1\2\0\1\11"+
    "\1\0\1\1\1\11\2\0\1\1\1\0\1\11\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[289];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public static class ErrorLexico
    {
        public String lexema;
        public int linea;
        public int columna;
        public String descripcion;

        public ErrorLexico(String lexema, int linea, int columna, String descripcion)
        {
            this.lexema = lexema;
            this.linea = linea;
            this.columna = columna;
            this.descripcion = descripcion;
        }
    }
    public ArrayList<ErrorLexico> listaErrores = new ArrayList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new ErrorLexico(yytext(), yyline + 1, yycolumn + 1, "No existe este símbolo en el lenguaje"));
    System.err.println("Error Léxico: " + yytext() + " en línea " + (yyline+1) + " y columna " + (yycolumn+1));
            }
          // fall through
          case 63: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 64: break;
          case 3:
            { return new Symbol(sym.NOT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 65: break;
          case 4:
            { return new Symbol(sym.PAR_IZQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 66: break;
          case 5:
            { return new Symbol(sym.PAR_DER, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 67: break;
          case 6:
            { return new Symbol(sym.POR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 68: break;
          case 7:
            { return new Symbol(sym.MAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 69: break;
          case 8:
            { return new Symbol(sym.COMA, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 70: break;
          case 9:
            { return new Symbol(sym.MENOS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 71: break;
          case 10:
            { return new Symbol(sym.DIV, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 72: break;
          case 11:
            { return new Symbol(sym.ENTERO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 73: break;
          case 12:
            { return new Symbol(sym.MENOR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 74: break;
          case 13:
            { return new Symbol(sym.IGUAL_ASIG, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 75: break;
          case 14:
            { return new Symbol(sym.MAYOR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 76: break;
          case 15:
            { return new Symbol(sym.ID, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 77: break;
          case 16:
            { return new Symbol(sym.PIPE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 78: break;
          case 17:
            { return new Symbol(sym.DIFERENTE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 79: break;
          case 18:
            { return new Symbol(sym.CADENA, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 80: break;
          case 19:
            { return new Symbol(sym.AND, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 81: break;
          case 20:
            { return new Symbol(sym.MENOR_IGUAL, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 82: break;
          case 21:
            { return new Symbol(sym.IGUALDAD, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 83: break;
          case 22:
            { return new Symbol(sym.MAYOR_IGUAL, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 84: break;
          case 23:
            { return new Symbol(sym.SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 85: break;
          case 24:
            { return new Symbol(sym.OR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 86: break;
          case 25:
            { return new Symbol(sym.DECIMAL, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 87: break;
          case 26:
            { return new Symbol(sym.FIN, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 88: break;
          case 27:
            { return new Symbol(sym.VAR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 89: break;
          case 28:
            { return new Symbol(sym.SEPARADOR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 90: break;
          case 29:
            { return new Symbol(sym.LEER, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 91: break;
          case 30:
            { return new Symbol(sym.FONT_ARIAL, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 92: break;
          case 31:
            { return new Symbol(sym.FINSI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 93: break;
          case 32:
            { return new Symbol(sym.HACER, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 94: break;
          case 33:
            { return new Symbol(sym.FIG_ROMBO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 95: break;
          case 34:
            { return new Symbol(sym.FIG_ELIPSE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 96: break;
          case 35:
            { return new Symbol(sym.INICIO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 97: break;
          case 36:
            { return new Symbol(sym.FIG_CIRCULO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 98: break;
          case 37:
            { return new Symbol(sym.COLOR_HEX, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 99: break;
          case 38:
            { return new Symbol(sym.MOSTRAR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 100: break;
          case 39:
            { return new Symbol(sym.FONT_VERDANA, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 101: break;
          case 40:
            { return new Symbol(sym.ENTONCES, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 102: break;
          case 41:
            { return new Symbol(sym.MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 103: break;
          case 42:
            { return new Symbol(sym.CONF_COLOR_SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 104: break;
          case 43:
            { return new Symbol(sym.CONF_LETRA_SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 105: break;
          case 44:
            { return new Symbol(sym.CONF_FIGURA_SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 106: break;
          case 45:
            { return new Symbol(sym.FONT_COMIC, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 107: break;
          case 46:
            { return new Symbol(sym.FIG_RECTANGULO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 108: break;
          case 47:
            { return new Symbol(sym.FINMIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 109: break;
          case 48:
            { return new Symbol(sym.CONF_COLOR_BLOQUE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 110: break;
          case 49:
            { return new Symbol(sym.CONF_LETRA_BLOQUE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 111: break;
          case 50:
            { return new Symbol(sym.FIG_PARALELOGRAMO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 112: break;
          case 51:
            { return new Symbol(sym.CONF_FIGURA_BLOQUE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 113: break;
          case 52:
            { return new Symbol(sym.CONF_LETRA_SIZE_SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 114: break;
          case 53:
            { return new Symbol(sym.CONF_COLOR_MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 115: break;
          case 54:
            { return new Symbol(sym.CONF_COLOR_TEXT_SI, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 116: break;
          case 55:
            { return new Symbol(sym.CONF_LETRA_MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 117: break;
          case 56:
            { return new Symbol(sym.FONT_TIMES, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 118: break;
          case 57:
            { return new Symbol(sym.CONF_FIGURA_MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 119: break;
          case 58:
            { return new Symbol(sym.CONF_LETRA_SIZE_BLOQUE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 120: break;
          case 59:
            { return new Symbol(sym.CONF_COLOR_TEXT_BLOQUE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 121: break;
          case 60:
            { return new Symbol(sym.CONF_LETRA_SIZE_MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 122: break;
          case 61:
            { return new Symbol(sym.CONF_COLOR_TEXT_MIENTRAS, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 123: break;
          case 62:
            { return new Symbol(sym.FIG_REC_REDONDEADO, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
