import java_cup.runtime.*;
import java.util.ArrayList;

/***** CÓDIGO DE USUARIO *****/
parser code {:
    public static class ErrorSintactico
    {
        public String lexema;
        public int linea;
        public int columna;
        public String descripcion;

        public ErrorSintactico(String lexema, int linea, int columna, String descripcion)
        {
            this.lexema = lexema;
            this.linea = linea;
            this.columna = columna;
            this.descripcion = descripcion;
        }
    }
    public ArrayList<ErrorSintactico> listaErrores = new ArrayList<>();
    @Override
    public void syntax_error(Symbol s)
    {
        String lexema = s.value != null ? s.value.toString() : "Token desconocido";
        listaErrores.add(new ErrorSintactico(lexema, s.left, s.right, "Se esperaba otro token"));
        System.err.println("Error Sintáctico: " + lexema + " en línea " + s.left + " columna " + s.right);
    }
    @Override
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        String lexema = s.value != null ? s.value.toString() : "Token desconocido";
        listaErrores.add(new ErrorSintactico(lexema, s.left, s.right, "Error sintáctico irrecuperable"));
        System.err.println("Error Sintáctico Irrecuperable: " + lexema + " en línea " + s.left + " columna " + s.right);
    }
:}

/***** TERMINALES ****/

/* Palabras Reservadas */
terminal String INICIO, FIN, VAR, SI, ENTONCES, MIENTRAS, HACER, MOSTRAR, LEER, FINSI, FINMIENTRAS;
terminal String SEPARADOR;

/* Configuraciones de SI */
terminal String CONF_COLOR_TEXT_SI, CONF_COLOR_SI, CONF_FIGURA_SI, CONF_LETRA_SI, CONF_LETRA_SIZE_SI;

/* Configuraciones de MIENTRAS */
terminal String CONF_COLOR_TEXT_MIENTRAS, CONF_COLOR_MIENTRAS, CONF_FIGURA_MIENTRAS, CONF_LETRA_MIENTRAS, CONF_LETRA_SIZE_MIENTRAS;

/* Configuraciones de BLOQUE */
terminal String CONF_COLOR_TEXT_BLOQUE, CONF_COLOR_BLOQUE, CONF_FIGURA_BLOQUE, CONF_LETRA_BLOQUE, CONF_LETRA_SIZE_BLOQUE;

/* Configuración Default */
terminal String CONF_DEFAULT;

/* Figuras permitidas */
terminal String FIG_ELIPSE, FIG_CIRCULO, FIG_PARALELOGRAMO, FIG_RECTANGULO, FIG_ROMBO, FIG_REC_REDONDEADO;

/* Fuentes permitidas */
terminal String FONT_ARIAL, FONT_TIMES, FONT_COMIC, FONT_VERDANA;

/* Operadores Aritméticos */
terminal String MAS, MENOS, POR, DIV;

/* Operadores Relacionales */
terminal String IGUALDAD, DIFERENTE, MAYOR, MENOR, MAYOR_IGUAL, MENOR_IGUAL;

/* Operadores Lógicos */
terminal String AND, OR, NOT;

/* Signos de Agrupación */
terminal String IGUAL_ASIG, PAR_IZQ, PAR_DER, PIPE, COMA;

/* Patrones */
terminal String ENTERO, DECIMAL, ID, CADENA, COLOR_HEX;

/***** NO TERMINALES *****/
non terminal ArrayList<FiguraDiagrama> programa, seccion_algoritmo, instrucciones, bloque_simple;
non terminal FiguraDiagrama instruccion, instruccion_simple, declaracion, asignacion, mostrar, leer, condicional, ciclo;
non terminal String expr_aritmetica, condicion;
non terminal seccion_configuracion, configuraciones, configuracion;
non terminal String expr_color, figura, fuente, indice_opt;
non terminal cierre_si, cierre_mientras;

/***** PRECEDENCIA DE OPERADORES *****/
// De menor a mayor precedencia
precedence left OR;
precedence left AND;
precedence right NOT;
precedence left IGUALDAD, DIFERENTE, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL;
precedence left MAS, MENOS;
precedence left POR, DIV;

/***** GRAMATICA *****/

start with programa;

/***** PRINCIPAL ****/

programa ::= 
    seccion_algoritmo:lista SEPARADOR seccion_configuracion
    {: RESULT = lista; :}
    ;

/***** SECCION DE ALGORITMO *****/

seccion_algoritmo ::= 
    INICIO instrucciones:lista FIN
    {:
        ArrayList<FiguraDiagrama> diagrama = new ArrayList<>();
        diagrama.add(new FiguraDiagrama("INICIO", "INICIO"));
        diagrama.addAll(lista);
        diagrama.add(new FiguraDiagrama("FIN", "FIN"));
        RESULT = diagrama;
    :}
    ;

instrucciones ::= 
    instrucciones:lista instruccion:inst
    {:
        lista.add(inst);
        RESULT = lista;
    :}
    | instruccion:inst
    {:
        ArrayList<FiguraDiagrama> lista = new ArrayList<>();
        lista.add(inst);
        RESULT = lista;
    :}
    ;

/* Instrucción de primer nivel (puede ser ciclo o condicional) */
instruccion ::= 
    instruccion_simple:i {: RESULT = i; :} | condicional:c {: RESULT = c; :} | ciclo:c {: RESULT = c; :}
    ;

/* Bloque interno para evitar anidamientos. Solo acepta instrucciones simples */
bloque_simple ::= 
    bloque_simple:lista instruccion_simple:inst
    {:
        lista.add(inst);
        RESULT = lista;
    :}
    | instruccion_simple:inst
    {:
        ArrayList<FiguraDiagrama> lista = new ArrayList<>();
        lista.add(inst);
        RESULT = lista;
    :}
    ;
    instruccion_simple ::=
        declaracion:d {: RESULT = d; :} | asignacion:a {: RESULT = a; :} | mostrar:m {: RESULT = m; :} | leer:l {: RESULT = l; :}
        ;

/***** INSTRUCCIONES SIMPLES *****/

declaracion ::= 
    VAR ID:id IGUAL_ASIG expr_aritmetica:e {: RESULT = new FiguraDiagrama("PROCESO", "VAR " + id + " = " + e); :}
    | VAR ID:id {: RESULT = new FiguraDiagrama("PROCESO", "VAR " + id); :}
    ;

asignacion ::=
    ID:id IGUAL_ASIG expr_aritmetica:e {: RESULT = new FiguraDiagrama("PROCESO", id + " = " + e); :}
    ;

mostrar ::=
    MOSTRAR CADENA:c {: RESULT = new FiguraDiagrama("IO", "MOSTRAR " + c); :}
    | MOSTRAR expr_aritmetica:e {: RESULT = new FiguraDiagrama("IO", "MOSTRAR " + e); :}
    ;

leer ::=
    LEER ID:id {: RESULT = new FiguraDiagrama("IO", "LEER " + id); :}
    ;

/***** ESTRUCTURAS DE CONTROL *****/

cierre_si ::= FINSI | FIN SI ;
cierre_mientras ::= FINMIENTRAS | FIN MIENTRAS ;

condicional ::=
    SI PAR_IZQ condicion:cond PAR_DER ENTONCES bloque_simple:bloque cierre_si
    {:
        FiguraDiagrama nodoSi = new FiguraDiagrama("CONDICION", cond);
        nodoSi.bloqueInterno = bloque;
        RESULT = nodoSi;
    :}
    ;

ciclo ::=
    MIENTRAS PAR_IZQ condicion:cond PAR_DER HACER bloque_simple:bloque cierre_mientras
    {:
        FiguraDiagrama nodoMientras = new FiguraDiagrama("CONDICION", "MIENTRAS " + cond);
        nodoMientras.bloqueInterno = bloque;
        RESULT = nodoMientras;
    :}
    ;

/**** EXPRESIONES ARITMÉTICAS ****/

expr_aritmetica ::= 
    expr_aritmetica:e1 MAS expr_aritmetica:e2 {: RESULT = e1 + " + " + e2; :}
    | expr_aritmetica:e1 MENOS expr_aritmetica:e2 {: RESULT = e1 + " - " + e2; :}
    | expr_aritmetica:e1 POR expr_aritmetica:e2 {: RESULT = e1 + " * " + e2; :}
    | expr_aritmetica:e1 DIV expr_aritmetica:e2 {: RESULT = e1 + " / " + e2; :}
    | PAR_IZQ expr_aritmetica:e PAR_DER {: RESULT = "(" + e + ")"; :}
    | ENTERO:e {: RESULT = e; :}
    | DECIMAL:d {: RESULT = d; :}
    | ID:id {: RESULT = id; :}
    ;

/***** CONDICIONES *****/

condicion ::= 
    expr_aritmetica:e1 IGUALDAD expr_aritmetica:e2 {: RESULT = e1 + " == " + e2; :}
    | expr_aritmetica:e1 DIFERENTE expr_aritmetica:e2 {: RESULT = e1 + " != " + e2; :}
    | expr_aritmetica:e1 MAYOR expr_aritmetica:e2 {: RESULT = e1 + " > " + e2; :}
    | expr_aritmetica:e1 MENOR expr_aritmetica:e2 {: RESULT = e1 + " < " + e2; :}
    | expr_aritmetica:e1 MAYOR_IGUAL expr_aritmetica:e2 {: RESULT = e1 + " >= " + e2; :}
    | expr_aritmetica:e1 MENOR_IGUAL expr_aritmetica:e2 {: RESULT = e1 + " <= " + e2; :}
    | condicion:c1 AND condicion:c2 {: RESULT = c1 + " && " + c2; :}
    | condicion:c1 OR condicion:c2 {: RESULT = c1 + " || " + c2; :}
    | NOT condicion:c {: RESULT = "!" + c; :}
    | PAR_IZQ condicion:c PAR_DER {: RESULT = "(" + c + ")"; :}
    ;

/***** SECCIÓN DE CONFIGURACIÓN *****/

seccion_configuracion ::= configuraciones ;
configuraciones ::= configuraciones configuracion | configuracion ;
indice_opt ::= PIPE expr_aritmetica | expr_aritmetica | ;
expr_color ::= expr_aritmetica COMA expr_aritmetica COMA expr_aritmetica | COLOR_HEX ;
figura ::= FIG_ELIPSE | FIG_CIRCULO | FIG_PARALELOGRAMO | FIG_RECTANGULO | FIG_ROMBO | FIG_REC_REDONDEADO ;
fuente ::= FONT_ARIAL | FONT_TIMES | FONT_COMIC | FONT_VERDANA ;

configuracion ::=
    CONF_DEFAULT IGUAL_ASIG expr_aritmetica | CONF_DEFAULT expr_aritmetica
    | CONF_COLOR_TEXT_SI IGUAL_ASIG expr_color indice_opt
    | CONF_COLOR_SI IGUAL_ASIG expr_color indice_opt
    | CONF_FIGURA_SI IGUAL_ASIG figura indice_opt
    | CONF_FIGURA_SI figura indice_opt
    | CONF_LETRA_SI IGUAL_ASIG fuente indice_opt
    | CONF_LETRA_SIZE_SI IGUAL_ASIG expr_aritmetica indice_opt
    | CONF_COLOR_TEXT_MIENTRAS IGUAL_ASIG expr_color indice_opt
    | CONF_COLOR_MIENTRAS IGUAL_ASIG expr_color indice_opt
    | CONF_FIGURA_MIENTRAS IGUAL_ASIG figura indice_opt
    | CONF_FIGURA_MIENTRAS figura indice_opt
    | CONF_LETRA_MIENTRAS IGUAL_ASIG fuente indice_opt
    | CONF_LETRA_SIZE_MIENTRAS IGUAL_ASIG expr_aritmetica indice_opt
    | CONF_COLOR_TEXT_BLOQUE IGUAL_ASIG expr_color indice_opt
    | CONF_COLOR_BLOQUE IGUAL_ASIG expr_color indice_opt
    | CONF_FIGURA_BLOQUE IGUAL_ASIG figura indice_opt
    | CONF_FIGURA_BLOQUE figura indice_opt
    | CONF_LETRA_BLOQUE IGUAL_ASIG fuente indice_opt
    | CONF_LETRA_SIZE_BLOQUE IGUAL_ASIG expr_aritmetica indice_opt
    | error ;