
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 55;
  public static final int CONF_COLOR_TEXT_MIENTRAS = 19;
  public static final int POR = 42;
  public static final int FIG_ELIPSE = 30;
  public static final int ENTERO = 58;
  public static final int SI = 5;
  public static final int MOSTRAR = 9;
  public static final int DIFERENTE = 45;
  public static final int FONT_COMIC = 38;
  public static final int ENTONCES = 6;
  public static final int FONT_TIMES = 37;
  public static final int SEPARADOR = 13;
  public static final int FONT_VERDANA = 39;
  public static final int FIN = 3;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int CONF_LETRA_MIENTRAS = 22;
  public static final int FINMIENTRAS = 12;
  public static final int OR = 51;
  public static final int IGUALDAD = 44;
  public static final int MIENTRAS = 7;
  public static final int DIV = 43;
  public static final int FIG_ROMBO = 34;
  public static final int ID = 60;
  public static final int CONF_COLOR_SI = 15;
  public static final int CONF_LETRA_SI = 17;
  public static final int COLOR_HEX = 62;
  public static final int DECIMAL = 59;
  public static final int EOF = 0;
  public static final int CONF_LETRA_SIZE_BLOQUE = 28;
  public static final int CONF_FIGURA_MIENTRAS = 21;
  public static final int CONF_FIGURA_SI = 16;
  public static final int error = 1;
  public static final int CONF_COLOR_TEXT_SI = 14;
  public static final int COMA = 57;
  public static final int CADENA = 61;
  public static final int PIPE = 56;
  public static final int MENOS = 41;
  public static final int MENOR = 47;
  public static final int PAR_IZQ = 54;
  public static final int CONF_COLOR_BLOQUE = 25;
  public static final int MAYOR = 46;
  public static final int FIG_REC_REDONDEADO = 35;
  public static final int CONF_LETRA_SIZE_SI = 18;
  public static final int CONF_COLOR_MIENTRAS = 20;
  public static final int FIG_RECTANGULO = 33;
  public static final int CONF_LETRA_BLOQUE = 27;
  public static final int MAYOR_IGUAL = 48;
  public static final int CONF_COLOR_TEXT_BLOQUE = 24;
  public static final int LEER = 10;
  public static final int FIG_CIRCULO = 31;
  public static final int CONF_DEFAULT = 29;
  public static final int HACER = 8;
  public static final int CONF_FIGURA_BLOQUE = 26;
  public static final int INICIO = 2;
  public static final int MENOR_IGUAL = 49;
  public static final int CONF_LETRA_SIZE_MIENTRAS = 23;
  public static final int FINSI = 11;
  public static final int IGUAL_ASIG = 53;
  public static final int FONT_ARIAL = 36;
  public static final int FIG_PARALELOGRAMO = 32;
  public static final int VAR = 4;
  public static final int MAS = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "FINSI",
  "FINMIENTRAS",
  "SEPARADOR",
  "CONF_COLOR_TEXT_SI",
  "CONF_COLOR_SI",
  "CONF_FIGURA_SI",
  "CONF_LETRA_SI",
  "CONF_LETRA_SIZE_SI",
  "CONF_COLOR_TEXT_MIENTRAS",
  "CONF_COLOR_MIENTRAS",
  "CONF_FIGURA_MIENTRAS",
  "CONF_LETRA_MIENTRAS",
  "CONF_LETRA_SIZE_MIENTRAS",
  "CONF_COLOR_TEXT_BLOQUE",
  "CONF_COLOR_BLOQUE",
  "CONF_FIGURA_BLOQUE",
  "CONF_LETRA_BLOQUE",
  "CONF_LETRA_SIZE_BLOQUE",
  "CONF_DEFAULT",
  "FIG_ELIPSE",
  "FIG_CIRCULO",
  "FIG_PARALELOGRAMO",
  "FIG_RECTANGULO",
  "FIG_ROMBO",
  "FIG_REC_REDONDEADO",
  "FONT_ARIAL",
  "FONT_TIMES",
  "FONT_COMIC",
  "FONT_VERDANA",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "IGUAL_ASIG",
  "PAR_IZQ",
  "PAR_DER",
  "PIPE",
  "COMA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CADENA",
  "COLOR_HEX"
  };
}

